### ISSUE TITLE
Buffer reallocation

### ISSUE THREAD

**Issue by Deymoss** [Framstag/libosmscout#1009]
Hello, Framstag, I'm render tiles with 4 threads, and when about 100-200 tiles rendered, Buffer reallocation starts to appear and very slows down rendering of tiles like this [pic](https://imgur.com/CmupGHa). If before that the tiles were rendered at a speed of 12-15 tiles per second, now 2-4, is there a way to get around the buffer reallocation? I found where this is happening, it's PushCoord func of Transformation .cpp. I make a project on Qt.

**Comment by Deymoss** [comment]
Or tell please what can cause buffer allocation, maybe it's my bad, and I can fix it.

**Comment by Karry** [comment]
Hi. 

Coord buffer is used for storing screen coordinates for all objects for one rendering cycle. It helps to avoid memory fragmentation and frequent allocations/deallocations... It may have some performance impact when it is reallocated, but it should not be very frequent. Are you using one renderer for each thread? Do you re-use renderers for multiple cycles? Did you profile your application? Are you sure that reallocations is bottleneck?

**Comment by Framstag** [comment]
The fact the the buffer is again and again resized to the same size means:
* It is too small in some situations ;-) This is not a problem but may hint that you are too many objects (and thus likely too much details). Do you use the default style sheet or did you make changes? I normally do not see reallocations at all.
* You are not reusing the CoordBuffer. Since the CoordBuffer is allocation the Renderer constructor, you are possibly not reusing the Renderer as much as you could. See for example the Tiler demo, that reuses the renderer for all tiles (in one thread).
* And yes, reallocation is not much more than a mem copy and thus should be have hight CPU overhead. It is though a sign of many objects in the rendering pipeline and such can of course reduce rendering performance.

Possibly debug by using the various debug flags to get the renderer to dump statistics to verify. See:

```c++
  void MapPainter::DumpStatistics(const Projection& projection,
                                  const MapParameter& parameter,
                                  const MapData& data)
  {
    if (parameter.IsDebugPerformance()) {
      log.Info()
        << "Data: " << data.nodes.size() << "+" << data.poiNodes.size() << " " << data.ways.size() << " " << data.areas.size();
    }

    if (parameter.GetWarningCoordCountLimit()>0 ||
        parameter.GetWarningObjectCountLimit()>0 ||
        parameter.IsDebugData()) {
      DumpDataStatistics(projection,
                         parameter,
                         data);
    }
  }

```

All comments by @Karry are (of course as always) valid, too :-)

Please keep us informed.

**Comment by Deymoss** [comment]
Thank you for answer! Yes I'm using 4 objects of one renderer like 4 threads. First of all, I must say what and how I am doing, I wanted to make a mobile map application for the squad to find people in the forest / difficult terrain. Therefore, I need offline maps to work in conditions when there is no Internet connection, so I need to render 17-19 zooms in order for the maps to be convenient to use, I need to track the route of people moving, and so on. Now to the point, I have separated the creation of coordinates for rendering the tile and the actual rendering of the tile. So that the rendering of 19 zooms did not take too much time, I decided to use multithreading, and so that offline maps could quickly place all the tiles on the screen, I made my own file format with ~ O (1) searching for the desired tile. There were problems and bugs, but we managed to solve them, it remains only to solve the problem with Buffer allocation, i'm already try to comment buffer overflow checking, but it was dumb and didn't help, trying many ways to solve problem but can't find a mistake in my code, if you have a little time please [check this out](https://github.com/Deymoss/Tiler). I know that I write bad code, and most likely you will experience severe pain when reading it, I apologize in advance :) problem will be on QueueBuilderClass or RenderClass, the rest of the classes are interfaces and auxiliary elements.

**Comment by Karry** [comment]
Well, looking just to `RenderClass`, I see that you are reusing renderer and you are reusing these threads. I am worry that your performance problems are not related with coord buffer at all. You should profile your application, at least with `perf top` and possibly check it with valgring. It seems to me that some objects are never freed (TileDataClass instances...), so your problems may be caused even by memory.

**Comment by Karry** [comment]
How many such "Buffer reallocation" messages you see when you divide it by number of htreads?

**Comment by Deymoss** [comment]
![Screenshot_20210226_105522](https://user-images.githubusercontent.com/33017837/109271912-37c76380-7821-11eb-9604-5754db2fc0d7.png)
![Screenshot_20210226_105544](https://user-images.githubusercontent.com/33017837/109271918-39912700-7821-11eb-8f7a-f21d8403dc00.png)
oh, it's probably threads slow down my program

**Comment by Deymoss** [comment]
> How many such "Buffer reallocation" messages you see when you divide it by number of htreads?

difficult to count, cause it is a little chaotic, can be 1 time on 36-50 tiles or 4 times in one place

**Comment by Deymoss** [comment]
> oh, it's probably threads slow down my program

but i write a simple qDebug on top of func run(), and the streams start as expected 4 times, from where 19300, I don't understand a little

**Comment by Deymoss** [comment]
![Screenshot_20210226_122306](https://user-images.githubusercontent.com/33017837/109281615-9692da00-782d-11eb-996b-ed7258554f23.png)
![Screenshot_20210226_122346](https://user-images.githubusercontent.com/33017837/109281623-985c9d80-782d-11eb-94d6-374068bdd1a3.png)
valgring, I hope I screened everything needed

**Comment by Framstag** [comment]
I tried to quickly build the application but I failed (would have to tune the QtCreator project too much).

Nevertheless from the frame graph I still assume you pass too much data (in the relation what is actually necessary to render the map) to the render so the renderer gets slow. IT will try to clip everything not needed for rendering but this still would take time.

From the code it looks like you never clear the data variable content. Is it possible that the vector just grow and grow?

I suggest to add some statistics dump regarding the size of the data struct members to RenderClass::MergeTilesToMapData(). The sizes for individual tile data counts should be related to the zoom level and the actual terrain rendered - thus should not steadily grow.

You also do some style sheet manipulation in the middle of RenderClass::run() (start of the while loop) I do not understand and thus I'm unsure if the leads to the right amount of data loaded for a tile.

**Comment by Deymoss** [comment]
> From the code it looks like you never clear the data variable content. Is it possible that the vector just grow and grow?
I don't think so, cause when thread takes next value from vector with function getNext in QueueBuilder, this value pop_back from vector, and count of values in 1 vector limited to 30 millions, so that the vector can take up a maximum of 2-2.5 gb of RAM.
>You also do some style sheet manipulation in the middle of RenderClass::run() (start of the while loop) I do not understand and thus I'm unsure if the leads to the right amount of data loaded for a tile.
thank you for note, i will check this.

I don't think I need to distract you with stupid questions, I hope I can figure it out myself.
Thank you very much for helping with understanding what a buffer reallocation is, before that I thought that it slows down, and was going to look for all its applications in the library and delete:)

Just the last question: if, after all, after fixing memory leaks, etc. there will be a redistribution of the buffer, what can this mean? It just seemed to me that the buffer is intended for situations when there is a device screen and only on it at that moment I need to render tiles, that is, a small amount, and when I need to render about 800 million tiles at a time, it overflows.

**Comment by Deymoss** [comment]
I think vector can't grow up to unexpected sizes, cause when thread takes struct with tile info by function getNext() from QueueBuilder i'm use pop_back and return tileInfo, and vector limited to 30 million values, which corresponds to 2-2.5 GB of RAM.

about styles thanks for note, i will check this moment.

Thank you very much for your help and answers to my stupid questions, I am already embarrassed to distract you when the problem does not apply to your library, I hope I can handle it myself, sorry that you had to look at my shitty code :)

just the last question: if, after all, after fixing memory leaks, etc. and the problem with reallocating the buffer will remain, what can this mean? It just seemed to me that the buffer is intended for situations when there is a device screen and only on it at that moment I need to render tiles, that is, a small amount, and when I need to render about 800 million tiles at a time, it overflows.

**Comment by Framstag** [comment]
The data you pass to the renderer are in the end just vector data consisting of points. Due to some style sheet processing the renderer may generate additional vector data, for example for parallel lines etc... All of these points must be transformed from geo coordinates to on screen coordinates to do things like clipping and actual on screen rendering. The CoordBuffer temporary holds this on screen coordinates. It gets allocated once during creation of the renderer. If you call render(...) it get filled in the first phases of rendering and gets (logically) cleared after all rendering for passed data is done. 

The size of the required CoordBuffer thus depends on the number of *points* passed to the renderer (which correlates to the number of objects passed). It also depends on the style sheet since this can result in additional points generated.

If you pass many complex objects (like a motorway) the number of points will be higher than if you just pass a small number of simple objects. That is the reason for feature like optimize low zoom areas and similar tricks, which try to reduce the number of points for an object already during import time. This is most important for low zoom situations in combination with a style sheet that requires relative many details/objects to be loaded - especially if object or geographically huge and have many details.

This is the reason why I asked for modified style sheets and map renderer parameter.

The reallocation of the buffer is not in it self bad. We need to have a good initial size for the buffer to avoid many reallocations during rendering. On the other hand having a too high default size might result in memory problems on small devices. But sometimes you want to render details and a happy with the renderer taking some more time. So we have have chosen an empirical good start value fo the array size, no more no less. 

If however there are many reallocations and the buffer grows and grows, this is a clear sign that something is wrong with the passed data.

**Comment by Deymoss** [comment]
ok, thank you for the detailed explanation, it turns out that I either have something wrong with the styles, or somewhere in the render cycle I recreate objects many times that should not be recreated so much .

one question to which I do not know the answer is why, when profiling, start_thread, run (), QThreadPrivate :: start () are called so many times if there should be only 4-7 creators and starts of new threads, although it is possible "сontext switch", but ~90% it's too much...

**Comment by Karry** [comment]
Profiler shows you how many times these methods was in sampled stacktrace. So, when 90% of your samples contains `start_thread`, it doesn't mean that this method is consuming 90% of your cpu power. But summary of all methods below. It is nicely visible in your flamegraph (your first screenshot).

It is clear that converting geo coordinates to screen coordinates consume huge amount of time. I may suggest you to enable linear interpolation for higher zoom levels. 

Just try to add 
```
projection.SetLinearInterpolationUsage(level.Get() >= 10);
```
to line 55 of your `renderclass.cpp`

**Comment by Framstag** [comment]
@Deymoss Please give us feedback if you succeed with our help and close the issue in case (and feel free to further asks, if not :-))

I did not understand you use case completely, but your are aware that you do not need to render tiles but also can render maps on the fly directly from the database without rendering intermediate tiles? Depending on your use case both may make sense, I just make to sure that you know all your options.

**Comment by Deymoss** [comment]
> I just make to sure that you know all your options.

yeah, i know about it, but I write maps for rescue teams, and I need to emphasize that they will never have an Internet connection, and smartphones, if you immediately render from a database on a smartphone, the battery will run out very quickly :)

**Comment by Deymoss** [comment]
> Just try to add

Thank you very much, i will try to use this

**Comment by Framstag** [comment]
I'm honoured to hear, that software I have written, helps rescuing people. I wish you good luck and if you need further help, tell us.

It would be cool if you would write a blog about it :-) We can always use some success stories. If you offer some photos and background information I could even try writing one for you.

**Comment by Deymoss** [comment]
> It would be cool if you would write a blog about it :-) We can always use some success stories. If you offer some photos and background information I could even try writing one for you.

now there is no point in writing, because I am not an experienced developer, from my code you can see that I barely reach the junior level, and I work on the project alone,  so I don’t I can predict if I will be able to complete the project fully. Because there is still a lot of work with the OpenStreetMap plugin to draw routes directly on the tiles and so on, but i will try my best to finish. When I bring the application into a usable state, I will definitely write to you and show you what I did.

Please tell me if I have any questions, how can I contact you? write here in the issue, either on social networks, or by mail?

**Comment by Framstag** [comment]
I suggest to use the issue tracker of GitHub for concrete problems or bugs and the mailing list for everything else.

The bug tracker allows us to keep track of concrete issue and make sure that every issue is handled and fixed (or at least documented). But for more general questions the mailing list is better since it has a better history and in principle reaches more people. It also needs some traffic ;-)

In the end we will red and react on both channels and suggest channel switch in case, so just "do" if you are unsure.

**Comment by Deymoss** [comment]
Ok, thank you very much for help, I didn't even expect that I would receive an answer, in any case I will find a way to contact you if something happens.
As a result, the reallocation of the buffer appears due to the fact that I transfer a lot of data in one execution of the program, and the library is designed for the most part to render one screen while using the program. But reallocation of the buffer does not have much effect on performance, and the rendering speed decreases due to the fact that I have memory leaks somewhere or a large number of objects are created, right?

**Comment by Deymoss** [comment]
I have no way to clear the buffer from renderClass?
i tried to do osmscout::coordBuffer().Reset() but usedPoints were not cleared

**Comment by Karry** [comment]
you are creating instance by this: `osmscout::coordBuffer()`

buffer used in painter is reset before every rendering steps here: https://github.com/Framstag/libosmscout/blob/30fe468e048a0f0e86be573c3a64c1d7885c2875/libosmscout-map/src/osmscout/MapPainter.cpp#L2166

**Comment by Deymoss** [comment]
and it can, in theory, overflow in one rendering cycle?

**Comment by Deymoss** [comment]
I understand that most likely my rendering is slowing down due to threads, because I have a Tiler that is written in pure C++ without threads and it works at the same speed regardless of buffer overflow, but I cannot understand how threads can slow down and why in my profiler 90% + this is start_thread, run () etc. But rather, this is a problem with threads and it's worth apologizing for the trouble and closing this issue, I initially thought that the problem was in the library and specifically in buffer allocation

**Comment by Framstag** [comment]
IMHO the problem is not the coordBuffer itself, but the data passed to the renderer.

If I for the first tile pass 10 ways with 10 coord each, I have to render 100 coordinates. It looks like that for the next tile you do render 10 ways with 10 coordinates each again. But you possible do not replace them but let them render on top so that the renderer render 20 ways with each 10 coordinates. 

It is obvious that after some time the coordinate buffer has to get enlarged. Please just count (and print out) the number of objects passed to the render on each cycle. I assume that it increases over time (and if not, we still have falsified a theory).

Multiple thread should not make the application crawl. Also multiple thread may result in each thread being slower than if you only render with one thread. But the application should not get slower *over time*. Also the libosmscout database will get under stress. However this should result in more IO - but again the app should get slower but not *over time*, too.

**Comment by Deymoss** [comment]
> Please just count (and print out) the number of objects passed to the render on each cycle.

I'm sorry, I didn't understand a little, I need to get the number of all objects that are in the renderer? And I don't really understand the phrase rendering cycle, I have it implemented as while on [line 47](https://github.com/Deymoss/Tiler/blob/main/renderclass.cpp), is this the rendering cycle? and on line 49, a structure that receives data about the next tile from, but this is one object that simply receives the following values every iteration.

I also think that multithreading should not gradually slow down the program, 100% somewhere endlessly objects are created and not cleaned up, but then the RAM would overflow, and then the paradox, the rendering slows down, the RAM occupied by the program is kept at the same mark, the CPU is 100% because of 4 threads, then what could be the problem, I have no ideas, I will carefully look with a debugger. 

and a little question, [is it normal coordinates in PushCoord func?](https://imgur.com/Qod9kub)

**Comment by Deymoss** [comment]
Recently I got the idea to check the entire rendering cycle using QElapsedTimer, 
`QElapsedTimer t;
        t.start();
        painter.DrawMap(projection,
                        drawParameter,
                        data,
                        &qp);
        qDebug()<<t.elapsed();`
I checked all the calls and found that DrawMap is initially executed in 50-100 ms, and after 600-800 tiles it is executed in 1200 ms, can you have any suggestions why this is happening? the library may not have been designed for multithreaded rendering and therefore unexpected results appear.

**Comment by Deymoss** [comment]
I tried to make MapPainterQt dynamic, and deleted it, but there were even more reallocations of the buffer, in the end I don't know why MapPainterQt is slowing down, can I get the buffer from protected into MapPaiter and put it in public to clear it in every render cycle?

**Comment by Framstag** [comment]
Hi @Deymoss 

My plan is to get your application to build and locally and take a look myself. 

However I'm currently ill and since for this I need some 2-3 hours spare time while having two kids thi may take a few days.

**Comment by Deymoss** [comment]
Sorry for spamming, I didn’t know that you are sick, do not rush then, look when it’s convenient, there are no special parameters for the command line, I just run through the qt 5.15.2 kit with the assembled libosmscout library, in pro file only libs like `LIBS += -losmscoutd \
            -losmscout_gpxd \
            -losmscout_mapd \
            -losmscout_map_cairod \
            -losmscout_map_svgd \
            -losmscout_client_qtd \
            -losmscout_importd \
            -losmscout_map_aggd \
            -losmscout_map_qtd \
            -losmscout_testd` and qt += core gui and `greaterThan(QT_MAJOR_VERSION, 4): QT += widgets`

**Comment by Karry** [comment]
Hi @Deymoss . 

> I tried to make MapPainterQt dynamic

It should not be needed. As you wrote, it will make situation even worse.

Btw, did you try to limit rendering process to single zoom level? Because higher zoom levels are more performance expensive in general. I have suspect that you are just catching the ghosts.

I was able to build Tiler, what arguments should I put to gui to test it? Which country you are using for import?

**Comment by Deymoss** [comment]
> I was able to build Tiler, what arguments should I put to gui to test it? Which country you are using for import?

Enter importedData Path: /home/deymos/imported_data
Enter stylesheet path: /home/deymos/SIMURAN/libosmscout/stylesheets/standard.oss
Enter top lattitude: 56.529
Enter left longituude: 21.094
Enter bottom lattitude: 50.938
Enter right longitude: 38.342
Enter start zoom level: 1
Enter end zoom level: 11
Enter name of plugin: osm_custom(or any name, depends on lib)

Do not pay attention to "fuck", it was I who checked whether I could read and display a tile from a binary file :) And about the single level, it doesn't matter, the render does not have time to pass the 11th level and is slowed down to 1 tile / s

**Comment by Deymoss** [comment]
omg 147 tiles/s, you are a wizard! I just didn't know about such a feature that data accumulates, I thought the buffer needed to be cleared every cycle, but the buffer lies in DrawMap in protected and I didn't want to move like a fool to public.

Sorry again for taking so much of your time. Thank you very much!

**Comment by Deymoss** [comment]
oh, forgot ro close issue, sorry
