### ISSUE TITLE
Enormous memory usage during Belarus import

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#1074]
During recent import of [Belarus OSM extract provided by Geofabrik](http://download.geofabrik.de/europe/belarus-latest.osm.pbf) import tool was killed by OOM (out of memory killer) on my machine (16 GiB ram + 22 GiB swap). It happened during optimizing areas for low zoom levels (step 21). Problematic type is `boundary_administrative`...

Commands to reproduce:
```
wget http://download.geofabrik.de/europe/belarus-latest.osm.pbf
wget http://download.geofabrik.de/europe/belarus.poly

Import \
  -d \
  --eco true \
  --typefile map.ost \
  --rawCoordBlockSize 60000000 \
  --rawWayBlockSize 4000000 \
  --relMaxWays 4096 \
  --altLangOrder en \
  --destinationDirectory europe-belarus \
  --bounding-polygon belarus.poly \
  belarus-latest.osm.pbf
```

Question is, if there is some bug created recently or data was just modified the way that is causing troubles? Other countries seems to be fine. Removing flag `OPTIMIZE_LOW_ZOOM` from `boundary_administrative` type workaround this issue.

**Comment by Framstag** [comment]
I reworked the complete OptimizeAreas step, but not any of the GenOptimizeXXX steps. Looking at the history https://github.com/Framstag/libosmscout/commits/master/libosmscout-import/src/osmscout/import/GenOptimizeAreasLowZoom.cpp there were recent smaller changes. If there is a bug, than because of the (in principle structural) changes to the transformation code I also recently did. However I did not change the transformation code itself, I just did heavy restructuring, so if this broke it, it should also be easy to fix.

**Comment by Karry** [comment]
I am expecting that problem is in the data file. But have no time for investigating it yet.

**Comment by Karry** [comment]
I randomly pickup four months old commit e185728cecce05fef59e12ec5ee928e2c3fff612 and it imports this data sets without issues. I will continue with git bisect, because I have no idea where is the problem.

**Comment by Karry** [comment]
I made simple bisect script, import is executed in cgroup with limited memory to 8 GiB (to avoid huge swap usage and fail fast):

```bash
#!/bin/bash
set -xe
cd $(dirname $0)
mkdir -p cmake-build-release
cd cmake-build-release

cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_UNITY_BUILD=OFF ..
make -j 8 Import

if [ ! -d /sys/fs/cgroup/memory/cgImport ] ; then
  CGUSER=$USER
  sudo cgcreate -t $CGUSER:$CGUSER -a $CGUSER:$CGUSER -g memory:/cgImport
  # 8 GB RAM
  echo $(( 8 * 1024 * 1024 * 1024 )) | sudo tee /sys/fs/cgroup/memory/cgImport/memory.limit_in_bytes
  # 8 GB swap, only works if you have swap
  echo $(( 8 * 1024 * 1024 * 1024 )) | sudo tee /sys/fs/cgroup/memory/cgImport/memory.memsw.limit_in_bytes 
fi

cgexec -g memory:cgImport \
  ./Import/Import \
    -s 0 -e 21 \
    -d \
    --eco false \
    --typefile ../stylesheets/map.ost \
    --destinationDirectory $DATADIR/europe-belarus/ \
    --altLangOrder en \
    --bounding-polygon $DATADIR/belarus.poly \
    $DATADIR/belarus-latest.osm.pbf \
  || exit 1
```
run bisect:
```bash
git bisect start e97df27a99d1458ad85167869b4b383fff3a1cfe 86b52ec0575a21a96576c647a978e39e38eb5b60 
git bisect run ./bisect.sh
```
And it identify first problematic commit as https://github.com/Framstag/libosmscout/commit/0bbcae5c861c4fd0047de9dc9197f36262858703

I will look on it later, why memory usage increased so much.

**Comment by Framstag** [comment]
Is your application crashing during area merging or one of the optimize steps. I do not see how changes in the one break a later step.

The changes parallelized the merging of areas. A merge thread is created for each CPU you have. The area types with the most candidates are merge first. AFAIK the memory consumption should not have changes, since all data for hold in memory for the sequential processing, too.

**Comment by Framstag** [comment]
@Karry We can close this issue now , too, since your patch is merged?
