### ISSUE TITLE
Use area visual center for label

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#1108]
We are using bounding box center for placing label on map. It is simple and fastest method. But for some natural areas, like islands or lakes its label may be located outside the area. For example ["Císařský ostrov" islet in Prague](https://www.openstreetmap.org/way/543187110):

![Snimek_20210806_001](https://user-images.githubusercontent.com/309458/129634488-48da6ffa-cf64-41dc-8b81-331dac001b3a.png)

It would be great to use some precise method for placing label on areas (rings). We can try to use [Polylabel algorithm from Mapbox](https://blog.mapbox.com/a-new-algorithm-for-finding-a-visual-center-of-a-polygon-7c77e6492fbc). This method should be fast, [code is available in C++](https://github.com/mapbox/polylabel) under terms of ISC license, that should be compatible with LGPL. It should be easy to adapt this code to libosmscout.

Not to degrade performace, this algorithm may be used just for some types. Or label position (visual center) may be computed during import time and stored in database.

**Comment by Framstag** [comment]
Yes, sounds interesting. I think import time would be wise for calculation. We can add it as an optional point to the polygon (triggered by some flag). Since we have to handle a huge number of polygons on import, we would need a very selective filter to even start the calculation - likely size (bigger buildings and bigger?) and possibly even types?

**Comment by Framstag** [comment]
I also think for relation based polygons there is a way to define the center. So this can be also evaluated?
