### ISSUE TITLE
Crash in Way::SetType()

### ISSUE THREAD

**Issue by vyskocil** [Framstag/libosmscout#1268]
I updated recently the OSMScout source code I use in my project and I'm now experiencing crashes in Way::SetType() when using it with the "_route" type which is used to draw the calculated path on the map.

The relevant code is : 

```routeWay``` is a ```WayRef```
```i``` is iterating between all active databases (here there are 2)

```
TypeInfoRef type=ctx->databases[i]->GetTypeConfig()->GetTypeInfo("_route");
if (type){
      osmscout::FeatureValueBuffer features;
      size_t layerFeatureIndex;
      features.SetType(type);
      if (type->GetFeature(osmscout::LayerFeature::NAME,
                                         layerFeatureIndex)) {
              auto*value=dynamic_cast<osmscout::LayerFeatureValue*>(features.AllocateValue(layerFeatureIndex));
              value->SetLayer(std::numeric_limits<int8_t>::max());
       }
       if(routeWay){
              // it crash there !
              routeWay->SetType(type);
              ...
```

This code is used to draw each map tiles

**Comment by vyskocil** [comment]
Here are some XCode screenshots that display the call stack
<img width="1656" alt="Screenshot 2022-05-19 at 12 04 51" src="https://user-images.githubusercontent.com/452704/169408368-aeff715b-9c70-40ea-8afb-ac7d82d67671.png">
<img width="1660" alt="Screenshot 2022-05-19 at 12 05 13" src="https://user-images.githubusercontent.com/452704/169408440-34900b43-85cf-43b9-adfd-d0783953865f.png">
<img width="1655" alt="Screenshot 2022-05-19 at 12 05 29" src="https://user-images.githubusercontent.com/452704/169408475-6c0a0749-608e-4e1d-bccd-abc11d25089a.png">
<img width="1660" alt="Screenshot 2022-05-19 at 12 05 43" src="https://user-images.githubusercontent.com/452704/169408495-567daee2-ab93-4e78-bac3-e1865198c6ad.png">

**Comment by vyskocil** [comment]
Sometimes it crash there : 
<img width="1638" alt="Screenshot 2022-05-19 at 23 16 13" src="https://user-images.githubusercontent.com/452704/169408768-fd72fe4d-32c0-4c3e-9ebd-70fae8f10597.png">
<img width="1637" alt="Screenshot 2022-05-19 at 23 16 36" src="https://user-images.githubusercontent.com/452704/169408780-994a51ca-38f1-402b-be59-6d27a5be5f53.png">

**Comment by vyskocil** [comment]
Hi @Karry !

Thank you for looking at this ! It seems better as it took longer to crash with my tests but it is still crashing somewhere further : 

<img width="1196" alt="Screenshot 2022-05-20 at 18 32 50" src="https://user-images.githubusercontent.com/452704/169573233-cbc95d19-ae28-4e52-b85d-c5582b58ad9e.png">
<img width="1195" alt="Screenshot 2022-05-20 at 18 33 10" src="https://user-images.githubusercontent.com/452704/169573246-f0eddd2d-9559-4cc6-bec7-fc51ad76eb00.png">
<img width="1196" alt="Screenshot 2022-05-20 at 18 33 29" src="https://user-images.githubusercontent.com/452704/169573259-d7de7b25-13e3-402e-9b58-503aafaad7fe.png">
<img width="1197" alt="Screenshot 2022-05-20 at 18 33 51" src="https://user-images.githubusercontent.com/452704/169573299-420dd57f-51d0-4464-a303-41e8422db7f4.png">
<img width="1195" alt="Screenshot 2022-05-20 at 18 34 12" src="https://user-images.githubusercontent.com/452704/169573321-61b9f8ae-b13c-4c3f-80fc-b060f752b4a5.png">

**Comment by Framstag** [comment]
Reopened the issue since merging the pull request does not mean, all problems are solved ;-)

@vyskocil : Please give feedback, if problems remain.

**Comment by vyskocil** [comment]
@Karry I recompiled all the libs and projet with ```-DCMAKE_CXX_FLAGS=-fsanitize=address``` but had to deactivate the ASAN option ```detect_container_overflow``` because I couldn't fix some of the "errors" (maybe there was some false positives ?). Sadly I'm not very fluent in C++ ...

But I could find the issue that we are look for here, it is a double free : 

<img width="1375" alt="Screenshot 2022-05-21 at 11 48 13" src="https://user-images.githubusercontent.com/452704/169646182-1fec1419-1c7f-48d1-9ca3-5be356450e42.png">

**Comment by vyskocil** [comment]
I fear that the issue is due to multi-threading which is not supported for OSMScout databases if I'm right...
This should be handled in my project using multiple "drawing context" with their private database handles but it seems there is some race conditions when using tiled rendering... I'll look at this in my code.

**Comment by Framstag** [comment]
* Access to the database itself should managed by using mutex where necessary, but it is possible that something is missing
* shared_ptr should be thread safe regarding the referencing the object or changing the reference
* So caching and dropping caches from multiple threads should be thread safe because of that
* Changing data via multiple threads however is not protected and not allowed (that would require a more special implementation of shared_ptr), suggestion is to copy objects on change if possible

**Comment by vyskocil** [comment]
Thank you @Framstag for the advises !
 Here is my new tile drawing code dealing with multiple databases and using render steps to try to achieve a good looking transition between the two maps at the borders. 
The crash occur (less frequently now...) because I have to dynamically add the calculated route path data when drawing each tile of the map which is not optimal but I don't know how to do it better ?

```
        std::vector<RenderSteps> renderSteps {
            FirstStep, DrawAreas, DrawWays, DrawHillShading, DrawLabels, LastStep
        };
        
        for (int step = 0; step < renderSteps.size()/2; step++) {
            
            RenderSteps startRenderStep = renderSteps[step*2];
            RenderSteps endRenderStep = renderSteps[step*2 + 1];
            
            // render the active maps
            for(int i = 0; i < ctx->mapServices.size(); i++){
                
                if (step == 0) {
                    std::list<osmscout::TileRef> tiles;
                    ctx->mapServices[i]->LookupTiles(projection,tiles);
                    ctx->mapServices[i]->LoadMissingTileData(searchParameter, *(ctx->styleConfigs[i]),tiles);
                    ctx->datas[i].ClearDBData();
                    ctx->mapServices[i]->AddTileDataToMapData(tiles, ctx->datas[i]);
                    
                    drawParameter.SetRenderBackground(false);
                    
                    if (drawParameter.GetRenderSeaLand()) {
                        ctx->mapServices[i]->GetGroundTiles(boundingBox,
                                                            ctx->magnification,
                                                            ctx->datas[i].groundTiles);
                    }
                    
                    // Append the routeWay and/or pathWay data in the last rendered database to paint it on top
                    if(i == ctx->mapServices.size() - 1 && (routeWay || pathWay)){
                        TypeInfoRef type=ctx->databases[i]->GetTypeConfig()->GetTypeInfo("_route");
                        if (type){
                            if(routeWay){
                                routeWay->SetType(type);
                                ctx->datas[i].ways.push_back(routeWay);
                            }
                            
                            if(pathWay){
                                pathWay->SetType(type);
                                ctx->datas[i].ways.push_back(pathWay);
                            }
                        }
                    }
                }
                
                ctx->mapPainters[i]->DrawMap(*(ctx->styleConfigs[i]), projection, drawParameter, ctx->datas[i], paintCG, startRenderStep, endRenderStep);
            }
        }
        
        // unlock the context drawing semaphore
        dispatch_semaphore_signal(ctx->drawSem);
```
        
 ```ctx``` is the drawing context which contains a semaphore and private open handle to databases, styleConfigs, datas,... The semaphore is acquired in a pool at the beginning of the drawing method thus each tile drawing should be independent.

**Comment by vyskocil** [comment]
Here is a sample of what I get at the border between France and Switzerland, the Switzerland database doesn't contain yet the elevation contour lines. 
There are some shift between some features and labels between the two databases I couldn't explain...

![IMG_3690](https://user-images.githubusercontent.com/452704/169661981-b64f0c1e-caff-4f2d-807c-dce2b4dff9be.PNG)

**Comment by vyskocil** [comment]
Regarding the shifted features and labels I think it could be due to the fact that the two databases were compiled with OSM data at some different dates...

**Comment by Framstag** [comment]
Each generated map has its own types.dat (in principle this means it has its own .ost file with its own content)and thus its own type configuration. It is possible that types in different maps (or better databases) are different, especially type ids and concrete values could be different.

Normally we do not make use of this, we try to assure that all maps share the same .ost file (and I hope that generation of TypeInfo is deterministic in this regard - types.dat possibly should be even identical regarding content?).

However, in the code we should keep data structures (or better instances of them) separated for each map, to avoid error because of intermixing and assume values that are not valid over each map.

The problems you have sound like you doing something like this, however I do not see the problem in your code. Especially, I do not see a problem in the code if for example I have a Way with a type from map a, and then I call setType() with a type from map b. While this should be avoided, it looks like the code just handles this fine. For cleanup the information from thr TypeInfo object from map a is used and for allocation the TypeInfo object from map b is used.

So I do not see the problem yet, however my answer still might help you, checking the correct semantics of your code. Stll some race condition could be another reason for random crashes.

Btw, you could cache a _route way for each database as long as it is thread safe handled and each database has its own instance. I'm not sure from your code snipped, if you already do that.

Is it possible to extract the code into a CLI application (perhaps even with a noop render backend), this way we could valgrind and sanitize to check the code (under a different OS)?

@Karry : Any other ideas, suggestions.

**Comment by Karry** [comment]
> Regarding the shifted features and labels I think it could be due to the fact that the two databases were compiled with OSM data at some different dates...

For icon, symbols and labels, I'm doing simple trick in Qt painting code - use one instance of label layouter for all renderers (all painters "delegates" layouter calls to the last one). As label layouter is not tied with specific database, it allows to handle label collisions between multiple databases...

**Comment by vyskocil** [comment]
Thank you @Framstag and @Karry for the analysis and suggestions, it made me think the lib would benefit having a kind of map database bundle object that would put together several OSMScout Database objects, I mean :
- several "country" maps compiled with the same style
- the basemap database for the whole world ground and seas
- overlay databases for certain kind of features that would benefit not being cut at "country" borders like elevation contour lines, country borders,...
We may assume all the databases could be imported with the same map.ost file even if some only contains a subset of all the types.

Then the map drawing and the routing code would take a DatabasesBundle to do their jobs, each of the contained database would have be marked as rout-able and/or draw-able. This is almost was is already done for the routing code when routing across borders and if I understood it well what the Qt map drawing code is partially doing  with the "trick" to share a common layouter.

What do you think about this suggestion ?

**Comment by vyskocil** [comment]
Here is a "proof of concept" screenshot of my app running on iPad using the concepts of the database bundle with two country databases (France and Switzerland), a world basemap database, a elevation contour lines overlay spanning across the whole Alps and the calculated route for a part of the GR5 hiking path drawn on top of it.


![IMG_DFC735ADB332-1](https://user-images.githubusercontent.com/452704/170873276-bf5d37d7-259d-4712-8f2c-15608ddb38cd.jpeg)

**Comment by Framstag** [comment]
>     * several "country" maps compiled with the same style
> 
>     * the basemap database for the whole world ground and seas
> 
>     * overlay databases for certain kind of features that would benefit not being cut at "country" borders like elevation contour lines, country borders,...
> 
>     * a "dynamic" overlay database that would be used to draw calculated route, paths,... from runtime generated geometries instead of compiled databases.

Currently, different sources do generate different datafiles than can eb handled completely independent from the other sources. Coastline is such an index which has a different structure than classic *.osm.pbf based data files.  Elevation files are similar. One other advantage is, that they have a simpler additive structure. Baseline is global, elevation is rectangular based, you can add datafiles without having to recaculate something.

Such a structure is also possible with OSM if you use a tile bases approach, however *.osm.pbf do not have such structure and you would have to preprocess them yourself.

This of course would have (big) impact in the used indexes for lookup.  Sound 

Sounds like you have similar ideas.

> Then the map drawing and the routing code would take a DatabasesBundle to do their jobs, each of the contained database would have be marked as rout-able and/or draw-able. This is almost was is already done for the routing code when routing across borders and if I understood it well what the Qt map drawing code is partially doing with the "trick" to share a common layouter.
> 
> What do you think about this suggestion ?

Yes, it makes sense to create another encapsulation layer that eases the use of multiple database files, similar to what we did with the routing. This is possible, since we have unique ids over database files (this was necessary for routing over multiple databases).

Looking at client-qt, DBJob.h and DBThread.h together with MapService.h offer such services that abstracts access to multiple database for rendering. The first two though use Qt signal/slot mechanismn, which would have to be replaces if we try to move parts of them into a more generic client library.

**Comment by Framstag** [comment]
@vyskocil Hmm, difficult to judge. Can/should we close the issue?

**Comment by Framstag** [comment]
Closing the issue...
