### ISSUE TITLE
Qt 6 Support

### ISSUE THREAD

**Issue by jheaff1** [Framstag/libosmscout#1280]
Hi,

Are there any plans to add support for Qt 6?

**Comment by Framstag** [comment]
For me the following question would be even more interesting:
* How big are the differences?
* What happens, if we just build with Qt6 (and possibly make some schematic changes)? How many errors will we get?
* How do we handle the migration? Do we make a copy of the existing libraries? Can we have some code branches (because the differences are small)? Howe do we make sure, that we do not have to fix and enhance things twice?

If you are interested in Qt6 support, this might help us starting to get a feeling how big the change would be?

**Comment by jheaff1** [comment]
Qt did change their licensing but I’m pretty sure that the free option hasn’t changed, I.e most of it is LGPL and some modules, eg QtCharts is GPL

**Comment by Framstag** [comment]
See merged request above.  I was now able to create a QT6 based build under Arch Linux using meson using the following command line:

```
PATH=/usr/lib/qt6:/usr/lib/qt6/bin:$PATH meson setup -D qtVersion=6 debug
```

I did the changes in the given way, since it was the easiest way, to see, how much was changed and how big the effort is, to get the code running under Qt5 and Qt6. With further findings the build configuration might have to get adapted.

To get continuous stable support for Qt5 and Qt6 one likely has to add another CI build against Qt6 dependencies.

The build currently fails because <QMediaPlaylist> has been removed from Qt6. See https://doc.qt.io/qt-6/qtmultimedia-changes-qt6.html

**Comment by Framstag** [comment]
I have now added a QT6 based build, see https://github.com/Framstag/libosmscout/pull/1300. The build currently is broken, due to Qt6 support not being complete yet.

**Comment by Framstag** [comment]
@Karry did add further fixes with #1318, but still more work to do.

**Comment by Karry** [comment]
Another round of fixes: https://github.com/Framstag/libosmscout/pull/1361

Build is green. But it is not tested and playing navigation voice instructions is not ported yet... See `NavigationModule` and `InstalledVoicesModel`

**Comment by Framstag** [comment]
Closing it. Qt6 support is there.
