### ISSUE TITLE
Generate 'types.dat'

### ISSUE THREAD

**Issue by mariantonia** [Framstag/libosmscout#137]
I’ve been trying to read a small map (31 KB) with the source code of DrawMapQt.cpp but gives me error:

> `Cannot load 'types.dat'! Cannot open database`

Which is obvious because i have only map.osm file (downloaded from osm web). Reading mailing list of sourceforge i realized that i need a sorted file and then generate a types.dat. Is that correct? How can I do that? 
My environment is: libosmscout compiled with mingw 5.3.0 (debug mode, protobuf, libxml2 , zlib, Qt 5.7, OSMSCOUT options by default). Win7 64.
I’ve been trying to recompilate libosmscout with OSMSCOUT_BUILD_IMPORT in the hope of existing a sorting tool but I am not shure about it.  Anyway I can’t compile because gives me error during compilation at 
`[ 58%] Linking CXX shared library libosmscout_import.dll
Warning: corrupt .drectve at end of def file
Cannot export ??_C@_00CNPNBAHC@?$AA@: symbol not found
libosmscout-import\CMakeFiles\osmscout_import.dir\build.make:1169: recipe for target 'libosmscout-import/libosmscout_import.dll' failed.`
Thank you very much!!!

**Comment by Framstag** [comment]
libosmsocut does convert *.osm or *.osm.pbf files into its own internal database format before it can be then used by the library for rendering, routing, lookup,...

See http://libosmscout.sourceforge.net/tutorials/Importing/ for how to import such files. Normally *.osm or *.osm.pbf fulfil the restrictions you named.

Regarding linking problems: It looks like you are using CMake build files? The build under MinGW is a little bit tricky and it sounds like linker cannot handle the objects files generated by the compiler - which normally should not happen.

To check, if the MinGW installation is not broken: Are you able to build simple C++ test files with your MinGW setup?

Are you using a 32bit or 64bit build?

We have some centrals builds for windows, see https://ci.appveyor.com/project/Framstag/libosmscout. Sadly the combination MinGW+CMake is broken since some time, because there seems to be problems with the appveyor setup of Qt. So I cannot state, that it definitely works - but it should. Perhaps the builds, configuration and setups for appveyor are still helpful for you to check your setup? Did you try the autoconf build (which does works, see Appveyor).

How experienced are you in C++ and using CMake, gcc toolchain, MinGW (this could help me suggesting the best analysis strategy)?

**Comment by mariantonia** [comment]
I've been using mingw compiler without problem until now since few months ago. Regarding my level of experience i must admit that I’m new with all this stuff of compiling 3rdparty libraries and other No-IDE-facilities tools :) 
I was trying to import osm files with the tutorial. First with bash script using gitbash (a linux-based shell that comes with github for winds):
Call:
 ../Import/src/Import  --typefile ../stylesheets/map.ost --destinationDirectory casa casa.osm
./build.sh: line 63: ../Import/src/Import: No such file or directory
Even when Import.cpp is in src folder. So i edit the script adding '.cpp' extension
Call:
 ../Import/src/Import.cpp  --typefile ../stylesheets/map.ost --destinationDirectory casa casa.osm
../Import/src/Import.cpp: line 1: /bin: Is a directory
../Import/src/Import.cpp: line 2: TravelJinni: command not found
../Import/src/Import.cpp: line 3: syntax error near unexpected token `C'
../Import/src/Import.cpp: line 3: `  Copyright (C) 2009  Tim Teulings'
Calling the importer by hand was
$ .../Import/src/Import \
> --typefile ../stylesheets/map.ost \
> --destinationDirectory casa \
> casa.osm
bash: .../Import/src/Import: No such file or directory

Yes I’m using CMake build files and minGW-w64. Sorry if i made a lot of silly and newbie questions. Thank you for all!!

**Comment by mariantonia** [comment]
I've been using mingw compiler without problem until now since few months ago. Regarding my level of experience i must admit that I’m new with all this stuff of compiling 3rdparty libraries and other No-IDE-facilities tools :) 
I was trying to import osm files with the tutorial. First with bash script using gitbash (a linux-based shell that comes with github for winds):
```
Call:
 ../Import/src/Import  --typefile ../stylesheets/map.ost --destinationDirectory casa casa.osm
./build.sh: line 63: ../Import/src/Import: No such file or directory
```
Even when Import.cpp is in src folder. So i edit the script adding '.cpp' extension
```
Call:
 ../Import/src/Import.cpp  --typefile ../stylesheets/map.ost --destinationDirectory casa casa.osm
../Import/src/Import.cpp: line 1: /bin: Is a directory
../Import/src/Import.cpp: line 2: TravelJinni: command not found
../Import/src/Import.cpp: line 3: syntax error near unexpected token `C'
../Import/src/Import.cpp: line 3: `  Copyright (C) 2009  Tim Teulings'
```
Calling the importer by hand was
```
$ .../Import/src/Import \
> --typefile ../stylesheets/map.ost \
> --destinationDirectory casa \
> casa.osm
bash: .../Import/src/Import: No such file or directory
```

Yes I’m using CMake build files and minGW-w64. Sorry if i made a lot of silly and newbie questions. Thank you for all!!

**Comment by Framstag** [comment]
The build.sh assumes that everything was build using autoconf and automake. In this the Import binary is placed under Import/src/Import. cmake though builds differently. So you have to adapt the build.sh file to lookup for the right binary. Since cmake use out of tree builds (that means, you create the build directory yourself) to have to lookup yourself where the binary is placed.

Note that Import.cpp is the source file. You cannot exchange the binary file as build by cmake or autoconf with the source file. They are simply not the same.

**Comment by mariantonia** [comment]
Thanks!!
