### ISSUE TITLE
Commit 'Assume that wstring is available' breaks compilation on Gentoo and Sailfish

### ISSUE THREAD

**Issue by rinigus** [Framstag/libosmscout#139]
Unfortunately, the latest commit breaks compilation on Gentoo (current setup, gcc 4.9.3). The error is
missing <codecvt>. Same issue is in Sailfish SDK.

**Comment by Framstag** [comment]
The old code (at least the importer) already assumed that std::wstring exists. The only real change should be the the way we convert UTF-8 strings (std::string) to std::wstring (see https://stackoverflow.com/questions/12493496/c-c-utf-8-upper-lower-case-conversions). 

So it would be nice to get the exact error message.

Nevertheless gcc 4.9.3 is very old. I though that gentoo is a rolling release distribution!? Why is the compiler that old?

For Sailfish, which likely has a more "fixed" dev environment I can accept an older compiler (though an update to 5.x should be managable, also C++11 is already 5 years old!). Nevertheless I also still need to get an exact error message to see how I can fix the problem without rolling back everything.

Note that my change is a preparation for better supporting case insensitive string comparison. Since the standard-compliant and platform independent way would be conversion to std::wstring, applying toupper or tolower and then converting back to std::string (utf-8). That is the currently main reason for my change.

I hope I can make std::wstring mandatory and only have to supply conversion code for utf8<=>wstring manually.

Please give me feedback!

**Comment by rinigus** [comment]
It fails on 

```
osmscout/libosmscout/libosmscout/src/osmscout/util/String.cpp:23:19: fatal error: codecvt: No such file or directory
 #include <codecvt>
```

I presume that Gentoo is conservative with respect to gcc. As it is, gcc 5x series is marked not stable. 

Taking into account that we need users to compile Import, it's important to have it compile on all kind of platforms :)

rinigus

**Comment by rinigus** [comment]
As a thought: should we look for boost library to do the same/similar things? In general, boost should be easier to add than changing libstdc++ in the system.

**Comment by Framstag** [comment]
See http://en.cppreference.com/w/cpp/locale/codecvt -> codecvt is C++11. Since 6.2 is already out, I'm not sure that gcc 5.x will switch from unstable to stable for gentoo ;-) Does not sound good :-/ Nevertheless, this is not the place to bash Linux distributions.

Libosmscout "try to restrict yourself to standard-library for hard dependencies as much as possible" policy made the library also support many systems. UTF8<=>WString conversion is a too small problem to justify an external library. I do value Boost, but up to now there was not a killer feature that "forced" my to use it. I likely will either fallback to OS (Linux, Windows) low level functions or reactivate the old code. 

Nevertheless, std::wstring is not the problem (it is the conversion). That is good :-)

I'll take a look.

**Comment by rinigus** [comment]
Yes, this is a problem. As far as I understood, it is a problem not with
gcc as such, but with the c++ standard library. Since I haven't managed to
pass compilation step, I am not 100% it will be all fine after linking. But
let's hope so :)

**Comment by Framstag** [comment]
OK, I have readded the conversion code fallback. I had to readd the check for the codecvt header and the check for the size of wchar_t. These have to be added to the cmake builfiles again, too. Please check.

**Comment by rinigus** [comment]
Thank you! I'll be able to check in few hours. Would do it for Gentoo and
Sailfish.

**Comment by rinigus** [comment]
Report: compiles nicely in Gentoo and Sailfish. I linked the server to new lib in Gentoo and have not seen any problems. It should be fine now.

**Comment by Framstag** [comment]
I assume you have used autoconf and did not make the necessary changes to the cmake files :)=)?

**Comment by rinigus** [comment]
No, I used cmake ... For Gentoo and Sailfish (Sailfish RPM script uses cmake). What's a catch? 

All I did, was pulling the latest version and compiling it. :)

**Comment by Framstag** [comment]
The cmake build files should check for the existance of the codecvt and calculate the size of wchar_t and write the results into the config.h. If you not do this, you would use the fallback on all systems, even if codecvt is available.

**Comment by rinigus** [comment]
OK, then I did everything correctly (`mkdir build; cd buid; cmake .. ; make; make install`). My main systems don't have codecvt, sorry.

**Comment by rinigus** [comment]
I guess this can be closed, right?

rinigus

**Comment by Framstag** [comment]
Right, with todays pushes, the cmake code should be in line with the autoconf code, again.
