### ISSUE TITLE
Is 2023.0325.2 a real release or a fake one?

### ISSUE THREAD

**Issue by MehdiChinoune** [Framstag/libosmscout#1398]
Could it added as a system package or not?

**Comment by Framstag** [comment]
Hi @MehdiChinoune, your question is not very concrete.

The mentioned release is a "real" release in the sense that it is a source release distribution, containing a buildable and tested version of the current code.

It is not a binary release for installation. This would be in principle possible, but I do not see this as a task of the libosmscout team itself, but of the distribution teams.

Also, since libosmscout is a library and does not offer production ready tools (only test applications) and production-ready tools would be the job of other teams, using libsosmscout, even a source distribution is of medium use.

I did added the possibility to make release and made a release to show that we steadily add features and generate stable versions ready to update to this code version (the last release was from 2018 and could have signaled that the project is dead, which it is not).

Why do you ask? What are your needs? In which role and situation regarding libosmscout are you in?

**Comment by MehdiChinoune** [comment]
> Why do you ask? What are your needs? In which role and situation regarding libosmscout are you in?

I am waiting to merge https://github.com/msys2/MINGW-packages/pull/16447

**Comment by Framstag** [comment]
I just release a new version, since Karry recently fixed some bugs.
