### ISSUE TITLE
Why so many build techs?

### ISSUE THREAD

**Issue by playgithub** [Framstag/libosmscout#1438]
e.g.
* cmake
* conan
* meson
* vcpkg

What abou t cmake only?

**Comment by Framstag** [comment]
What about meson only ;-)

The actual reasons:
- we started with make and dropped it in favor of cmake, since it was better, simpler and faster
- we then made use of meson because it was just more of it: *much* simpler and thus better - and sometimes slightly faster
- we did not drop cmake, because cmake integration into IDEs (Visual Studio, Visual Studio Code and CLion) is much better still. If you ask me, I personally would drop cmake, if IDEs catch up. But people may have different opinions.
- we made use of conan and vcpkg because we had installation and dependency management problems under Windows. Getting the few dependent libraries installed, build and compatible is a major pain.
- vcpkg is currently the winner, but requires local builds of everything (though this might change). conan claims to be better, but the last time I checked, it did not work better. So vcpkg is the way to go.
- Note that conan and vcpkg are not build tools, but dependency management tools.
- We did not drop conan (but didn't test or maintain it either), because things may change.

Hope that helps.

**Comment by playgithub** [comment]
For building techs, it's better if it save developers more brain power for either learning and using.
`vcpkg` meets the demands.

I have no experience with `meson`, but if it is nice, I'd like to learn it even just for fun.

I think few people like `cmake`, but they have to learn `cmake`, anyway `cmake` can be used easily, and `vcpkg` can be used even more easily, and `cmake` is friendly with `vcpkg`.
