### ISSUE TITLE
Build fails because Config.h isn't installed

### ISSUE THREAD

**Issue by syyyr** [Framstag/libosmscout#1564]
Hi, since 8c875b6940026bf70a427f1061c31bf94960987d, `osmscout/private/Config.h` is included transitively inside public headers. However, `Config.h` is not installed, which means that applications can't include these public headers. Since it's inside the `private` directory, it probably isn't supposed to be installed, so I'm not sure what's correct solution.

**Comment by Framstag** [comment]
Hi Václav,

you are right. Historically the Config.h names are not namespaced and thus the header should not be included in public headers. For this there is (in this case, since the name are different for each library) CoreFeatures.h that should be used for this.

Can you supply a pull request for this (this would make sure that everything fits your problem) or ydo you expect us to fix this? In the later cae please make a github issue to track the fix.


On 05.03.24 15:07, Václav Kubernát ***@***.***> wrote:
> Hi, since 8c875b6 
> <https://github.com/Framstag/libosmscout/commit/8c875b6940026bf70a427f1061c31bf94960987d>, |osmscout/private/Config.h| is included transitively inside public headers. However, |Config.h| is not installed, which means that applications can't include these public headers. Since it's inside the |private| directory, it probably isn't supposed to be installed, so I'm not sure what's correct solution.

Best wishes
Tim

**Comment by syyyr** [comment]
I will supply a PR.
