### ISSUE TITLE
ubuntu18.04

### ISSUE THREAD

**Issue by user-Mrh** [Framstag/libosmscout#1577]
Can it be installed in Ubuntu18.04 ? I get an error with " libosmscout-master/libosmscout/src/osmscout/io/File.cpp:22:10: fatal error: filesystem: No such file or directory
 #include <filesystem>"

**Comment by user-Mrh** [comment]
#include <filesystem>

**Comment by user-Mrh** [comment]
#include ”filesystem“

**Comment by Framstag** [comment]
I'm not sure, but I assume that the compiler in Ubuntu 18.04 is too old. As you can see in https://github.com/Framstag/libosmscout/tree/master/ci/docker , we have docker based build tests for Ubuntu 22.04 and 24.04. We dropped 18.04 two years ago (https://github.com/Framstag/libosmscout/commit/833a8731f070a31e288a0c107e2a0a9180a30b37). From the comment just because of your error.

You likely still can use Ubuntu 18.04, but you have to be sure to use a recent compiler (and cmake). See https://github.com/Framstag/libosmscout/commit/a3ed0781b73a019ec5ef2d3b2c855aeccb6db624 , where we dropped Ubuntu 20.04, because its cmake was too old.

Hope this helps. Note that you can also use meson as a build system, but you also need a rather current meson version, so possible you run into similar constraints.

**Comment by Framstag** [comment]
@user-Mrh : As this is no error in libosmscout itself, I would like to close the issue. Is this OK for you? OR do you have any questions?
