### ISSUE TITLE
Render sea/land on database polygon only

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#189]
Hi. Current client-qt code tries to combine more map sources. Multiple osmscout databases or even online map (tiled DB thread). It is using database bounding box to determine what source covers given area. This aproach is good approximation, but it fails when you use databases for neighboring countries, like Czechia and Austria...

It would be great when would be possible query to database polygon (Covers database this bounding box?) and sea/land will be rendered inside this polygon only.

It is possible to store such information to water index without changing format? I have limited knowledge about this data file, but it seems to be right place to me...

**Comment by Framstag** [comment]
The WaterIndex offers cells for various zoom levels where each cell has either the state "water", "ground" or "unknown".

What you are likely are interested is the state "unknown" that is either set, if there is no data, it is also returned outside the bounding box of the database (which is a simple rectangle). It can also be returned if there are big holes in the data (the "is this cell water or ground" has some configurable limits).

If you do not render "unknown" tiles or only if there is no database covering this cell, the result should already be better.

For implementation of cross-database routing we need similar information. Cross-database routing will only work well, if there is some certain overlap between database borders. For To know in which database to look for a routing node, we need some coverage map. I'm currently thinking of a simple bitmap, where a bit signals that there is at least one routing node in this cell. So if we are currently following the A* routing graph we can check in which database we have to look for (partial) routing data for a given (route)node.

Only open question is, how big should the bitmap cells be (zoom level) to fulfil the following requirements:
* Cells should not be too big, so that we do not always query all routing databases but only in border regions.
* Cells should not be too small, because the bitmap needs a certain disk space

After these basic calculations the implementation of such index should be simple. It though would only return information, if the cell contains route nodes. A similar index with more general information is though possible, too.

Does this help you?

**Comment by Framstag** [comment]
Can we close this now after we merged?

**Comment by Karry** [comment]
Sure, we can.
