### ISSUE TITLE
Invalid (prefill?) tile cache data

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#201]
Hi Tim. I have some weird rendering issues on my phone. When I start application on zoom level 5 and slowly zoom in to level 10, application shows me different (incorrect) result than when I restart application and render level 10 with clean caches.

I was not able to reproduce it locally (I was trying about an hour), but it is relative simple to reproduce it on mobile. Because of that, I started bisect search of change that cause that. I found that this problem started with 9b6ce6f1d8d69af602da481fb048d9e5b1275f9f

Can you please review this commit if there is something what is obviously wrong? I will look at it too tonight or morning.

Correct result with library at ee44879831609268ae5ea93d325255844ff9f348
![cache_bug_correct](https://cloud.githubusercontent.com/assets/309458/21818923/eac6e242-d769-11e6-947c-a8bc0a8e5295.png)

Incorrect at 9b6ce6f1d8d69af602da481fb048d9e5b1275f9f
![cache_bug_incorrect](https://cloud.githubusercontent.com/assets/309458/21818937/fc4888ae-d769-11e6-9003-412f5a322d5a.png)

**Comment by Framstag** [comment]
To make the analysis of the patch easier: If you are directly loading and rendering data for zoom level 10 you see more or less data get rendered, a if you zoom from level 5 to level 10? Viewed from the style sheet which result is correct?

The problem is not reproducible with OSMSCout2 on the desktop? Is the data loading and rendering code the same?

**Comment by Karry** [comment]
It seems that it render less data than it should. 

correct ee44879831609268ae5ea93d325255844ff9f348 ([full log](https://gist.github.com/Karry/67cfede34ba47220339800aa247109fd)):
```
Draw: [49.61071 N 14.06250 E - 50.28934 N 14.76562 E] 1024x/10 1168x1752 219.00000 DPI
*** Buffer reallocation: 262144
Paths: 1257/476/476/32 (pcs) 0.015/0.339/0.003/0.000 (sec)
Areas: 13576/3559/7118 (pcs) 0.080/0.223/0.002 (sec)
Nodes: 245+0/245 (pcs) 0.045/0.000 (sec)
Labels: 80/1/81 (pcs) 0.314 (sec)
```

broken 9b6ce6f1d8d69af602da481fb048d9e5b1275f9f: ([full log](https://gist.github.com/Karry/dd7efb3a702eea6b2f7a7ccc859a71a5))
```
Draw: [49.61071 N 14.06250 E - 50.28934 N 14.76562 E] 1024x/10 1168x1752 219.00000 DPI
Paths: 732/431/431/41 (pcs) 0.007/0.244/0.003/0.000 (sec)
Areas: 369/82/164 (pcs) 0.002/0.020/0.000 (sec)
Nodes: 245+0/245 (pcs) 0.037/0.000 (sec)
Labels: 78/1/79 (pcs) 0.596 (sec)
```
First one returns same result as on OSMScout2 on desktop, it should be correct with stylesheet.

I can't reproduce it with OSMScout2 (plane rendering) StyleEditor (tiled rendering) nor DrawDemoQt :-( rendering code, parameters and stylesheet is the same.

**Comment by Framstag** [comment]
I suggest to drop the call in MapService to prefill data based on the parent tiles (tiles of the next lower zoom level). This is just an optimization and should break anything (under the assumption that all code is correct ;-)).

The patch does two changes. Changes to the tile data API and changes to the prefilling. If you drop the prefill stuff we should see if the problem is in this half..or the other (divide and conquer). You expensive is it for you to do this or add debug output (time needed for such "roundtrip")?

**Comment by Framstag** [comment]
It looks like the problem you have is related to timing. That would at least the (for me) most obvious explanation, why you cannot reproduce it on the desktop. But I do not see any change relation to multi threading, timing or locking.  One major change was, that AddXXXData now always adds the data, where the Set method before exchanged the old content with the new. This was compensation in the calling code (and the reason for the changes o the prefill code). This should however not result in less data (on error) but more data.

**Comment by Karry** [comment]
Hi. I am able to reproduce it locally, on PC with OSMScout2. Trick is that you have to setup huge tile cache to make sure that parent tiles will not be evicted from the cache and you have to zoom in with key (+). I don't understand why it don't happen when zoom in with mouse wheel :( 

Try this branch: https://github.com/karry-space-with-my-second-forks/libosmscout/tree/prefill-tests 

If I understand correctly, optimized area/way files can return different objects for different zoom levels. Different sets of objects, or with different geometrics. So when there is no wood returned for level 5 (these objects are just small), this type is pre-filled to child tiles and wood is skipped in `MapService::GetAreasLowZoom`. Solution can be to always load all optimized objects - remove `requestedAreaTypes.Remove(cachedAreaTypes);`.

**Comment by Framstag** [comment]
Ahhhrrghh! Thanks, that sound like a reasonable explanation. I'll drop prefill optimized ways and areas from parent tile.

**Comment by Karry** [comment]
Actually, it make sence to prefill it, but it should be "replaced" by objects for current zoom level when it is loaded... I am just curious, what zoom levels are "optimised"? From 0 to 10, or just subset?

**Comment by Framstag** [comment]
The prefilling is done to avoid database access. In this case you are right that the data cannot be fetched from the parent tile since it is just not the same data.

There is currently no logic for contains suboptimal data that has to be replaced after loading. But this would in principle possible. The TileData would just need an additional type/data slot for this.

You are right in that it makes sense to try to prefill as much as possible. Actually it is likely that the *neighbouring* tiles already have some of the data we need. Current if a way or area is parts of two tiles it will get loaded twice. The problem with neighbouring tiles is that getting the right data is more complicated, since you cannot simple do "get all of that type" as with the parent tile. So you would have to look in the neighbouring tiles and correlate the data there with the list of offsets returned from the node/area/way index and then still have to load the rest of the data not available in the neighbouring tile. This would require some more locking and one has to see if this will make things faster.

**Comment by Karry** [comment]
> Current if a way or area is parts of two tiles it will get loaded twice.
Hmm, there will be always something that can be improved...

Thank you for your patience and final fix.

**Comment by Framstag** [comment]
To answer the question regarding "which levels get optimized":

```c++
          for (uint32_t level=parameter.GetOptimizationMinMag();
               level<=parameter.GetOptimizationMaxMag();
               level++) {
...
```
