### ISSUE TITLE
Duplicate entries in tile cache

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#223]
Hi. I prepared simple change that prints tile cache content on cache destruction: https://github.com/karry-space-with-my-second-forks/libosmscout/commit/92c83d83e8fa9e314908c62749810aeac2aa36c1

With OSMScout2 code, plane rendering uses asynchronous data loads, new load may start even previous one is still running. It causes duplicates in tile data (way with one file offset is loaded more than once to the one tile) and huge memory overhead.

`cat cache.log | grep ">" | grep w | sort`
```
...
> 14.12751.8849 w 83604414 (0x7f3bc0d6ec20)
> 14.12751.8849 w 83604414 (0x7f3bc1ae7640)
> 14.12751.8849 w 83604414 (0x7f3bc2f7f800)
> 14.12751.8849 w 85165921 (0x7f3bc0d4a470)
> 14.12751.8849 w 85165921 (0x7f3bc1ae7740)
> 14.12751.8849 w 85165921 (0x7f3bc2f804b0)
```

**Comment by Framstag** [comment]
Hello Lukas, if I understand it correctly, the problem is, that a tile is loaded multiple times in parallel and thus data is added twice to the same tile?

**Comment by Karry** [comment]
It is my guess. It is ok with synchronous loads. I will try to look deeper on this issue...

**Comment by Framstag** [comment]
The MapService works in that it starts one thread per index file (node, way, area, opt. ways, opt. areas). Each thread has a working queue. This makes sense, since some index files are single threaded anyway and multit-hreaded access to a file may be not that of an improvement anyway. The advantage of this design: There should be no race condition regarding an individual tiles being handled twice, because this design should guarantee that a tile data structure is effectively filled single threaded.

There could be still situations where multi-threading is a problem. Access in prefilling and index loading at the same time...or a missing guard somewhere. However the TileData Set/Add methods are also protected via a mutex.

So I assume that there is some algorithmic problem, like forgetting to remove duplicates between prefill and index data (though they should be disjunct based on their type) or similar...Though AddTileDataToMapData() explicitly uses a map/set to avoid this.
