### ISSUE TITLE
Research on missing parts in germany border

### ISSUE THREAD

**Issue by aquiles2k** [Framstag/libosmscout#253]
This issue is for collecting information regarding missing pieces in the germany country border relation.

The following image shows some of the gaps:

![border_de](https://cloud.githubusercontent.com/assets/6095108/23088393/5b32f932-f57c-11e6-8c91-75ecfe13c955.jpg)

The following image zooms on one of the gaps and shows one of the missing lines in openstreetmap.org

![map_de_boundary](https://cloud.githubusercontent.com/assets/6095108/23088428/b3582bc8-f57c-11e6-9926-d6f2263f86e8.png)

**Comment by aquiles2k** [comment]
The relation for the germany border is 51477
https://www.openstreetmap.org/relation/51477

![border_de_51477](https://cloud.githubusercontent.com/assets/6095108/23088465/2766ebf8-f57d-11e6-9a2a-62ecc69380a8.jpg)

**Comment by aquiles2k** [comment]
I checked DumpData on 51477 but it doesnt gave me anything usefull. Here is the start:

Area {
  OSM id: 51477
  fileOffset: 1076932141
  type: boundary_country
  boundingBox: [47.27011 N 5.86631 E - 55.09916 N 15.04193 E]
  center: 51.18464 N 10.45412 E
  cell level: 4

  Name: Deutschland
  AdminLevel: 2

  master
  Name: Deutschland
  AdminLevel: 2

The rest is just about 120.000 lines with nodes

**Comment by aquiles2k** [comment]
[log_ger2.txt](https://github.com/Framstag/libosmscout/files/784632/log_ger2.txt)

Thats my import log but nothing interesting there too. The only lines for country boundary seem unrelated:

Line 25519:    Type boundary_country: 0 node(s), 13 area(s), 1313 ways(s)
Line 25743:    !! Cannot resolve way member 148678119 for relation 16239 boundary_country 
Line 25787:    !! Cannot resolve way member 463949542 for relation 49715 boundary_country 
Line 25788:    !! Cannot resolve way member 89475933 for relation 50046 boundary_country 
Line 25790:    !! Cannot resolve way member 410344167 for relation 51684 boundary_country 
Line 25791:    !! Cannot resolve way member 122990455 for relation 51701 boundary_country 
Line 25794:    !! Cannot resolve way member 28988617 for relation 52411 boundary_country 
Line 27128:    !! Cannot resolve relation member 1627999 for relation 1111111 boundary_country 
Line 27877:    !! Cannot resolve way member 144035032 for relation 2171347 boundary_country 
Line 27897:    !! Cannot resolve way member 28494719 for relation 2202162 boundary_country 
Line 27974:    !! Cannot resolve way member 42825429 for relation 2323309 boundary_country 
Line 32646:    Reduced ways of 'boundary_country' from 1313 to 123 way(s)
Line 32684:    Splitted long ways of 'boundary_country' from 123 to 582 way(s)
Line 33339:    Type boundary_country, 752 cells, 1460 objects
Line 33435:    Writing map for boundary_country , 25.2 KiB

**Comment by aquiles2k** [comment]
I didnt find any mentioning of the example way 186276174 anywhere so it could either been merged through libosm or it had never been in the data at all.

Is there anything i can do to find out more? Any code pointers where i could make the importer print out the merged ways?

**Comment by aquiles2k** [comment]
Ok i put in some debug and came up with this for the sample way:

`Merging way 186276174 into 76030976`

76030976 is not part of the border but a water stream

https://www.openstreetmap.org/way/76030976

So it looks like a bug on libosm side?

**Comment by Framstag** [comment]
I can reproduce it. Merging of ways is done after relation building. So this should not be a problem. Multipolygon relations should always result in closed areas to be drawn. Interesting enough this does not seem to be the case here...

Further investigation is needed. I see the following potential causes:
* Data in *.osm.pbf file is not the data in the OSM master database
* Relation building is somehow broken
* Rendering is somehow not correct

**Comment by aquiles2k** [comment]
Interesting, ill look into relation building then. 

What do you mean by the first potential cause? How could i check rendering?

**Comment by Framstag** [comment]
Applying some more debug output it looks like the relation is actually not drawn. If you look at the style sheet it says:

```
[TYPE boundary_country] WAY {color: @countryBorderColor; displayWidth: 0.4mm; dash: 7,3;}
```
So the rendered is triggered for the individual ways, not for the relation! I'm currently trying to get the relation drawn. But that fails (checking further).

Of course if the individual ways are drawn, then ways might be missing and the boundary might be incomplete.

**Comment by aquiles2k** [comment]
Oh yes now that you say it that, makes sense. 

But isnt it still a bug that he merges a country boundary way (which is also a water stream way) into a way which is just a water stream way? So he basically lost all that type info when downgrading it to just a waterway.

**Comment by Framstag** [comment]
OK, the problem with the relation not drawing was caused by some accidental debugging code. 

So if you draw the AREA (by defining its border in the style sheet) you get the actual multipolygon relation drawn. This works smoothly and the border is complete.

If you draw the WAY, you get all ways of this type drawn. This boundary is not complete.

But all this is not a bug :-)

Reason: In the relation you might reference ways (and areas) of types, which are not the same of the relation. This allows you to reuse existing objects. If for example part of the border is a river, you would just reference for this part of the border the river.

I assume that this is used for *this* boundary, too. Parts of the relation are not itself object of the required type.

Side note:
* There is possibly more room for blacklisting (and thus further on removing) objects from the database. 
* If you only draw the relation, some incomplete boundaries are not drawn.

```
  TYPE boundary_country
    = WAY AREA ("boundary"=="administrative" AND "admin_level"=="2") OR
      RELATION ("type"=="boundary" AND "boundary"=="administrative" AND "admin_level"=="2")
      {Name, NameAlt, AdminLevel}
      MULTIPOLYGON IGNORESEALAND
```
In the case, where we only rely on the multipolygon relation, we actually could drop the ways from the database.

**Comment by Framstag** [comment]
If you agree,please close the issue.

**Comment by aquiles2k** [comment]
Cool, ill check it.

**Comment by aquiles2k** [comment]
Ok just one question before i close this. 

It makes sense that when drawing the ways that there might be holes. But the example way 186276174 actually was one of the boundary ways and could have been drawn, if it werent merged with another way into just a water stream way. Since the relevant data for this issue is still intact in the relation i'll call it radical optimization in this case :) But couldnt it be that on some other ways there will be lost information?

Anyway thanks for helping debugging this!

**Comment by Framstag** [comment]
If you look closely at https://www.openstreetmap.org/way/186276174 it is a administrative boundary *and* a water stream. in libosmscout objects however only have one type. types are given in the order of the map.ost. Since stream comes before boundary, internally this is a stream. This also explains why it is merged with another stream typed object.

In OSM you can tag as you will, but normally objects should only have one leading type, all other attributes add information to this type.

coastlines are exceptions boundaries seem to be one, too.

The importer thus dumps any ways with the tag/value combination "natural"/"coastline" into a separate rawcoastline file. And thus separates coastline handling from normal processing. For proper administrative boundary handling thus would have to be done, too. The current handling of boundaries is nevertheless sub optimal since it results in drawing of large objects. Technics like they are done in the water index should get applied to this type (and possibly some others on demand), too. However coastlines and boundaries have their differences and thus code cannot be just duplicated.

**Comment by aquiles2k** [comment]
Ok, thanks for the explanation.

Border looks good now when drawing as AREA.

![map_de3](https://cloud.githubusercontent.com/assets/6095108/23095170/d03bd026-f605-11e6-917a-a1a44aa5da1d.jpg)
