### ISSUE TITLE
Suggested import improvement: Merge near areas with same features

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#27]
Hi Tim. When I am playing with map, I often see row of building simplified to triangles. You can see it in this screenshot: ![this screenshot](https://cloud.githubusercontent.com/assets/309458/16224622/1e97b77a-37a3-11e6-88cc-d4a435d04dbd.png)

Here with closer zoom: ![Here with closer zoom](https://cloud.githubusercontent.com/assets/309458/16224623/1e978f52-37a3-11e6-97b1-6319a1675c39.png)

How complex would be to merge these areas that are sharing more than one point into one before optimize step? I think that this kind of optimization should reduce number of geometries in city areas and produce smaller database...

**Comment by Framstag** [comment]
That may already be possible. The map.ost file documentation says:

    MERGE_AREAS:
      Areas of this type that "touch" each other and the same attribute values
      will get merged.    

MERGE_AREAS is currently set for a number of area types, where there is no obvious information loos, if connected areas will be merged (it will always have some effect like labels rendered differently because the center of the area has change during merging).

You can of course set MERGE_AREAS also for the building type. I haven't actually this yet, but it may work. Note however also that the merge is only done, if two areas not only have the same type, are connected, but they must have the same features with the same value. So if you have connected buildings, but they have different house numbers, they will not be merged.

The merge will also cost you cpu and memory, if you merge a huge numberc of objects -  and an import normally has many buildings :-)

The current code of course be adapted :-) I would suggest to play with it a little and make a more precise feature request if the current code does not work as requested.

**Comment by Framstag** [comment]
You idea is of course valid. It is just that this should always be just an option, since it results in information loss (which is acceptable or not depending on the actual needs).

**Comment by Framstag** [comment]
In above case areas would be merged during import. That means, the merge is visible in all zoom levels, original data is lost. Since building are likely not visible in "OptimizedArea" mode it does not make sense, to implement it there.

Optimizing during rendering IMHO is more CPU intensive than just rendering it. My measurements show, that calculation of text boundaries is already measurable expensive (and thus something that should be cached), so complex area joining algorithms definitely will be, too.

**Comment by Framstag** [comment]
Hello, I did not get any answer from you regarding this issue. Did my answer help you, should I close the issue? Did I misunderstood you?

**Comment by Karry** [comment]
Hi. Sorry that I don't write some resolution. I don't have time for experimenting with MERGE_AREAS yet... But I will close this issue, you answer my question. Thanks.
