### ISSUE TITLE
Add an optional world overlay for offline maps [$50]

### ISSUE THREAD

**Issue by aquiles2k** [Framstag/libosmscout#283]
As already discussed some times on the mailing list it would be nice to have a simple world overlay on top of which the "real" maps would be drawn.

Some discussion on the mailing list: https://sourceforge.net/p/libosmscout/mailman/message/35671245/

@rinigus mentioned a nice website which already provides shapefiles with land polygones in various complexities: http://openstreetmapdata.com/data/land-polygons

If these are not sufficent or for other reasons one could also think about importing the data by oneself using there corresponding tools in https://github.com/osmcode/osmcoastline

They have for example a tool called "osmcoastline_filter" which extracts only coastlines from a pbf file and puts it into a new one.

**Comment by Karry** [comment]
Hi. I like the idea, but it is real issue? In meaning that we should fix something or develop something new. It should be possible to generate database for complete world from such simplified data files. And client Qt API already support multiple databases (ok, one think that may cause problems is db ordering, but it may be fixed by one sort)...

Just try it and report issues that you will find :-)

**Comment by rinigus** [comment]
I guess the real issue (at least for me) is how to get such world overview in. If its all possible then a readme would be of help as well. I would be happy to introduce such overlay into the server, for example.

I am not sure plain sort would be sufficient. As far as I understand, plain map drawing right now does not take into account the polygon surrounding it. In other words, we throw all possible map data on a rendered surface one after another and hope for the best. The containment issue, which becomes important for world overlay as well, is not resolved. Please correct me if I am wrong.

**Comment by aquiles2k** [comment]
Im downloading planet.osm.pbf atm (35GB) and will try the osmcoastline_filter tool afterwards to get a world coastline pbf file (hopefully). I'll then can test how it behaves. Unfortunately im soon away over the weekend so dont expect any results soon :)

**Comment by Karry** [comment]
@rinigus : You can create directories manually with order: `level0_world` `level1_germany` and  `level2_berlin` finally... Then, simple sort databases by its directory manes makes sense ;-) Or you can sort it by bounding box size (descent), it is more general...

**Comment by aquiles2k** [comment]
Sorry could you elaborate a little? How would i specifically sort the database in code and why is it needed in the first place?

**Comment by Framstag** [comment]
Regarding helpful or not: 
* It would be helpful to have coastlines for the whole world as a background available. This way we do not need to move into unknown outside the import data. The step effect at the polygon borders would disappear.
* It also depends how good (performance, memory usage) the WaterIndex handles coastlines for the whole world and how big the resulting index would be.
* If the resulting index would be of small size we could even move the generation of such index into its own separate global database. Since however the index for south america is already ~300MB I assume that the the index size is too big for such approach. We should however take a look if we could not reduce the size of the index without loosing precision (by for example dropping the last index level).
* The current approach results from the fact that getting global coastline data is costly, data is most of the time broken and index size is too big and every byte on mobile is expensive.

If I have multiple databases that overlap in covered area the question is in which order do I draw the data in the overlapping areas. My approach again would be to have a list of cells (completely) covered by a database. Such list can be generated by evaluating the clipping region of the original data. In such case I can just draw the cell (tile) only from one database.

f this does not work I can still load data from all databases covering the cell and the merge the data by removing duplicates. The question is, how do I identify duplicates? Currently route nodes have a global id, areas, ways and nodes in general do not have such id (anymore). I would have to compare objects by looking at their coordinates, length and type to compare them.

**Comment by Framstag** [comment]
And we need to able to parse shapefiles anyway to use the data form openstreetmapdata...

**Comment by aquiles2k** [comment]
Bounty added 💰 

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=43354189)](https://www.bountysource.com/issues/43354189-add-an-optional-world-overlay-for-offline-maps?utm_source=43354189&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by aquiles2k** [comment]
I tried to compile the above mentioned osmcoastline tool under mingw but the dependencies are giving me headaches, so no progress from this side :(

**Comment by Framstag** [comment]
This is something I could take a look at in holiday. If anyone else is faster, no problem.

**Comment by Framstag** [comment]
Got a simple shape file parser working that can parse and remerge the coastlines from http://openstreetmapdata.com/data/coastlines.

```
...
581307 costlines
```
Lets see next, if the data retrieved does make sense. Most coastlines are very small, around 10 are (much) bigger. Could be continents...

**Comment by Framstag** [comment]
![bildschirmfoto von 2017-06-02 12-43-28](https://cloud.githubusercontent.com/assets/14061582/26722785/cd9e4096-4791-11e7-9cdc-2867728032af.png)

Here are screenshot of the hacked water index with all the coastlines from the shape file mentioned above. It is not yet clear, if the shape file contains errors regarding russia north coastline or if there is an error in the water index generation code.

**Comment by aquiles2k** [comment]
Wow, thats looking really cool, so cool that im getting greedy and already think about how nice country borders would look like :D

**Comment by Framstag** [comment]
We now have a BasemapImport, that generates a water.idx from the global shape file.

* Download WGS84 shapefile from http://openstreetmapdata.com/data/coastlines
* copy the *.shp file into your maps diretcory as coastlines.shp
* Create 'world' sub directory
* Call the basemapImport as `../BasemapImport/src/BasemapImport --destinationDirectory world --coastlines coastlines.shp`
* Copy the resulting world/water.idx into one of your database directories, overwriting the import-specific index with the more general one. Start OSMScout2.

Next steps:
* Create a BasemapDatabase and BasemapService or similar
* Enhance MapPainter so that it can draw the general tiles first
* Extend OSMScout2 to get it to draw (could get tricky)
* Fix all these annoying bugs regarding Mercator projection limits that are now much more obvious :-/
* Write documentation

**Comment by Framstag** [comment]
OK, we now have our first working version for OSMScout2:
* OSMScout2 not silently tries to load the basemap by assuming that it is ../world in relation to the database passed to the command line. @Karry: I do not want to mess with your core more than necessary. I'm sure I have broken something or at least did it not the way you would. Feel free to improve my code. With issue #294 the API should get better for you.
* OSMScout2 still seems to have problems with the range limits imposed by the Mercator projection. If you zoom to level 0 and move around you quickly get it to break.  I assume that the reason is, that the MercatorProjection does not check if it is valid (and sets valid=false) or better rejects invalid input parameter. I'll see, if I can fix that. I added checks to the return codes of the Projection class, so possibly after fixing the projection OSMScout2 will already work smoothly.

Next steps:
* Fix all these annoying bugs regarding Mercator projection limits that are now much more obvious :-/
* Write documentation

Nearly done. Jipy!

**Comment by Framstag** [comment]
I tried to fix the problems by saving/restoring  state in Mercator projection. But this seams to fix some but not all problems. It looks like we need also some fixes in OSMScout2, since its internal state seems to get broken, if setting a projection fails. I assume that we have to enhance the API of the MercatorProjection to make in turn OSMScout2 happy. I make a new issue for this (See issue #356).

I'll see that I now write some final documentation and then would wait for feedback before closing the issue.

**Comment by Framstag** [comment]
Documentation updated. Waiting some time for feedback.

**Comment by aquiles2k** [comment]
Looks fine to me (besides the behaviour on north and south pole 😃). Would accept it for the bounty.

**Comment by Framstag** [comment]
Fine. Since nobody else raised his voice, I'm closing the issue. If there is still a problem, of course one can make a new issue.
