### ISSUE TITLE
Better rendering of multiple databases

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#294]
With current Qt client api map databases are painted to canvas one by one. Implementation is here: https://github.com/Framstag/libosmscout/blob/master/libosmscout-client-qt/src/osmscout/PlaneDBThread.cpp#L441

There can appears some errors on database boundaries. For example ways or labels covered by areas:

![database-boundary](https://cloud.githubusercontent.com/assets/309458/24820554/f8ab4208-1be9-11e7-9499-e7c853148afc.png)

How to improve this situation? I have two ideas:
 - rewrite `StyleConfig`, `MapPainter` to be independent on database (`TypeConfig`), merge data from all databases before paint and then use one `MapPainter`
 - expose painting steps from `MapPainter` (prepare, ground tiles, areas, ways, labels...) as public api and paint map by "layers" with multiple MapPainters...

**Comment by Framstag** [comment]
StyleConfig, MapPainter are dependend on the database, because they need to interpret the FeatureValueBuffer based on concrete type information offered by TypeConfig (which in turn is offered by the database). Joining data this way would enforce all databases being imported using the identical map.ost. Currently you can still mix versions.

Merging data from all databases is not easy, because the is no simple definition of identity. Objects are (likely) equal because they have the same length of nodes and (all) nodes have the same id (coordinate and serial id).

The first question to ask: Do databases overlap? If they overlap are there always regions, that contain equal data by definition? If yes, we do not need to merge data, we just need to render data in a way that we render (sub tiles) with data from either one database. This would possibly the simpler solution.

And if this is not the case: Can we possibly change the import to fix this? If not, we are back to your suggestions...

**Comment by rinigus** [comment]
Just few comments from my side. 

First, regarding the overlapping of the databases. Yes, databases of the neighbouring countries overlap. This is due to the new common practice of splitting the planet that way that it keeps the relationships intact. So, for example, if one node is in Germany on the border, the whole line/polygon relationship will be incorporated into Germany PBF as well as into the other country. So, some data will overlap, but not all.

When we discuss rendering of the multiple databases, I would like to consider https://github.com/Framstag/libosmscout/issues/57 as well as https://github.com/Framstag/libosmscout/issues/287 . 

Routing through multiple databases would probably require some API where we would be able to specify which databases are available. Why not to design the API so, that we could take advantage of specifying multiple databases in rendering as well? As such, rendering does not require it if we overlay layer after layer from each database separately (to avoid areas drawing on top of labels, for example), but it would surely be convenient to be able to specify list of available databases to libosmscout and let it route/render them together. 

Label intersection requires that the labels rendered from multiple databases would be aware of each other. In my mind that means that we would need to have single MapPainter handling painting of the data by from multiple databases. When I implemented multiple database rendering in Mapnik, that's exactly what was done: layer-by-layer (areas, roads, labels, pois) data was pulled from multiple databases and painted. 

I very much like @Karry's suggestions and I think they would be required to implement rendering of multiple databases properly. The both suggestions are possible. In Mapnik, its done via exposing steps as a public API allowing you to paint layer after layer.

**Comment by Framstag** [comment]
Regarding adding a layered API to MapPainter:
* This should be possible. Problem with that is that we introduce more state than be had before. Before we had one entry point. Attributes of the Painter had either the state "constant after initialisation" or "temporary state to be flushed after rendering". Now with layered rendering, we have to keep the temporary state until the last layer is rendered. We need some protocol (in form of an API) for this (BeginMapRendering(),...RenderXXX(), FinishMapRendering()). Backends like SVG possibly are not able to fulfill the protocol, so perhaps use of a interface-like baseclass using multiple inheritance.
* Regarding merging: Merging of data of course would also make things (much) simpler, but merging is not simple. For database size reasons object do not have a unique id. OSMId is uint64_t, that would be 8 additional bytes for every node, way and area. Either we have to reintroduce the id, find a simpler id and smaller (like we did for coordinates with the serial id) or merge by "soft" equality, which will be much more expensive. Merging between tiles of the same database is much simpler, since we have the file offset as unique identifier. This will not do between databases ;-)

General comment: We currently highly depend on the geofabrik exports, which are more or less boundary based. I could image a alternative approach where we build databases for rectangular regions. This way we possibly could make some more assumptions, there would be no overlap (have to find a strategy to always define a clear "owner tiler" for every object).

**Comment by rinigus** [comment]
Re merging: I wouldn't propose merging as such. Maybe it would be possible to use layered approach that has loop through the databases hidden from the user and implemented on the library side? In the end, I think we must assume that there are the same objects in the both extracts.

Re Geofabrik exports: its possible to convert even such export into the tiles / rectangular regions. But even then we would be facing questions about overlap. For example road between Germany and France. If we move to tiles, I presume we would have to cut the objects straight on the border of tiles.

**Comment by vyskocil** [comment]
This is a somewhat different case of multiple database rendering, here I try to merge the world basemap and a single country database and we can see that there are artifacts at the country borders and coastlines. To obtain this rendering I load the ground tiles from the base map and append the ones from the country database into the list then draw the given tile.
Perhaps the solution to have a almost perfect merge would be to use the world basemap waterindex when importing the country database and do the correct choice between sea or land at the borders (actually the country is like a island surrounded by seas) and add missing lands in the seas that are outside the boundaries of the country (like the north of Sardinia in my sample picture that is covered by the sea of the south Corsica tile) 
![img_8078](https://user-images.githubusercontent.com/452704/28994696-e4dab21a-79d4-11e7-86ad-0498d8307009.PNG)

**Comment by vyskocil** [comment]
I forgot to say that the issue arise from the fact that the basemap is a simplified version of the real coastlines at a lower resolution to save (a lot of !) space, otherwise it should be sufficient to not paint sea area from the country database... but this lead to other artifacts around the coast at high zoom level...

**Comment by rinigus** [comment]
I am not sure its a lot of space to specify coastlines for the World in the precision that would be sufficient for rendering it at any precision. From Mapnik experience, it takes 712 MB for World coastlines allowing you to go high z-levels, as used in practice. Since Mapnik uses it in double precision, I would expect to be able to reduce it further. When using TWKB format, I was hitting 400-500MB range. I wouldn't be surprised if its possible to get even smaller footprint if Tim will look into it (speaking from empirical experience based on comparing libosmscout database sizes with the rest).

While requirements are considerable, all the problems with the coastlines would completely disappear. You could take them out from the country maps and render sea-coast relationship using World basemap only.

**Comment by vyskocil** [comment]
Regarding space it take I'm speaking about the actual database produced by the BasemapImport tool that is contained in only one file : water.idx.

By default it generate magnification levels from 4 up to 10 and the file is about 700 MB, I pushed it to level 12 and the resulting file is then about 2.5GB ! I abandoned the (crazy) idea to go up to level 18 or 20 which is what should be needed to have "perfect" coastlines at street level magnification...
Here is a sample of the coastline artifacts we can see when using a water.idx basemap with levels upto 10 and zooming to a higher level the whole map : 

![img_8073](https://user-images.githubusercontent.com/452704/28996125-abe41260-79f9-11e7-95f9-46b026da093a.PNG)

**Comment by rinigus** [comment]
Great that you tested it. Well, that means that the current water.idx is not optimal. Coastline shapefiles are about 700 MB allowing you to get z18-20, without any issues, as far as I can see. Maybe it would be better then to switch into rendering shapefiles (or something similar) to cover World coastlines.

**Comment by vyskocil** [comment]
Perhaps it is not optimal but this is not a simple shapefile, it has the information about what is water and what is land a any point of the globe with some precision (zoom level).
I think this file should be used (optionally) when importing a database to store information about sea/land in the border tiles (tiles that are partially inside the bounding box polygon) as I tried to explain in my first post.

**Comment by Framstag** [comment]
The water.idx should store the individual level and especially the coastlines rather optimal, though there are still optimizations possible, which would though slightly decrease access and/or render performance though. 

What is not optimal is, that it stores many levels. Where is level is (at least) 4 times bigger than the level before. The reason for this is, that we want a good balance between details and performance. The more detailed the coastline for a given level is, the more points it has and the slower it renders. I would suggest though to experiment to only calculate every twice or even third level, perhaps this is still "good enough" but with even more reduced on disk size.

For a water.idx for the whole world things are even less optimal. Reason is, that water.idx uses a bitmap for signaling on one hand the type of the tile and on the other hand it contains the offset to the optional coastline data.

For the world by far most tiles do not hold coastline data. This gets worse the higher the zoom level is. See the output for level 10:

```
   Writing index for level 10, 1050625 cells, 36334 entries, 4 bytes/entry, 157,6 MiB
```

Each bitmap entry contains 4 bytes, though we only would need two bits for the type:

```
    enum Type {
      unknown = 0,
      land    = 1, // left side of the coast
      water   = 2, // right side of the coast
      coast   = 3
    };
```

So, water.idx IMHO does store coastlines rather good and it likely has a good approach for weighting details vs. speed on all zoom levels. But it is by far inefficient, if storing region where there is no coastline.

This should be easy to fix. Have a simple bitmap or rect/tree based index for rough signaling (rectangular) regions of water, land and coastline region and only store tiles as we do now for coastline regions. As we have already have a bitmap for each level in memory, it should be simple to apply such optimizations on it. I would assume that we should gain factors of reduction in disk storage space.

Any volunteers? I just started to work on improving the free string input location search.

**Comment by Framstag** [comment]
I just changed (and pushed) the MapPainter base class to offer a special Draw-method that allows you to trigger individual internal render steps. This would allow to better coordinating rendering of tiles form multiple map sources.

**Comment by Karry** [comment]
With recent improvements, rendering is much better on boundary of two databases. There are remaining minor issues - labels are located separately for each database, huge areas from one database may overlap smaller areas from second database... But the main problem why I created this issue is gone (areas from one database overlap labels from another). So I am closing this issue.

I am suggesting to create new issue, If you want to discuss remaining issues, or implementation of "layered" rendering for other renderers (it is done just for Qt renderer, see `MapPainterBatchQt`).
