### ISSUE TITLE
Postal Code Boundaries [$50]

### ISSUE THREAD

**Issue by aquiles2k** [Framstag/libosmscout#322]
Hi its me and my postal codes again :) (#112 #262)

If thats ok i'd feature request to add some way to optionally indvidually import the complete postal code boundaries and make it searchable.

See
- http://wiki.openstreetmap.org/wiki/DE:Konsolidierung_der_PLZ-Relationen_in_Deutschland_2013
- http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dpostal_code

This would allow us:
- search for postal codes independent of direct addresses (no need for postal code tag defined in houses/ways or nodes | we can get the postal code of the cabin somewhere in the wilderness)
- as a result we could remove the postalCode FeatureReader and save some space for people not interestes in postal codes
- improve search by looking for locations in a postal code boundary (e.g. search for lesser known city munich in 04938 not the popular munich in 80331–81929, 85540 )

The first thing always happens for me in areas where theres no postal code defined on the individual house level. But with an optional postal boundary one could simply look for the surrounding postal code area.

The last part is especially usefull in a situation where the user already inputs a whole address which normally includes the postal code. Without the postal code search restrictions, a programm basically has to reask which munich hes talking about because it finds both. And then the user gets annoyed because he already stated through the postal code which munich he meant.

**Comment by Framstag** [comment]
Analysis: I see the problem. Having bounding box relation evaluated could enable us to calculate postal code for object that do not explicitly have the postal code set.

In the resulting index though IMHO boundaries should not be visible, since they lead to false assumptions. Also postal code boundaries are not always available (in foreign countries) and they would be difficult to generate from raw data. So the index should allow search for postal code but should not correlate postal code with some area.

IMHO this thus has to be split into two issues:
* First: Index the current postal code information available on the objects itself, enhance the current index and extend the location search to also support search for postal codes.
* Second: Evaluate optional existing postal code boundaries and make use of them to add postal code information for objects that do not have such postal code explicitly set.

Both parts of of category "medium" to "big" and thus the index should be split anyway :-)

@aquiles2k: Do you agree?

**Comment by aquiles2k** [comment]
Sounds reasonable to me, depending on what you mean with the second point. 

It sounds like you want to add postal codes through boundaries at import time to all which doesnt have one set. This sounds like a huge overhead. E.g. if i want to ask for the postal code at a specific coordinate, somewhere in the wilderness. For this to work you'd have to set the postal code on ALL objects like areas and ways etc.. 
If on the other side you just have an bounding area defined. You could "just" ask if the coordinate in question lies within.

**Comment by Framstag** [comment]
I assume that postal code boundary are only available in a smaller subset of countries. So the postal code index must also work without them and still produce reasonable results.

Currently the location index is a tree of regions (counties, cities, suburbs,...). Each region contains a list of containing POIs, locations and addresses for locations. The idea now would be to move an postal code indirection between the region and its data. So for example for a Region "Dortmund" I get a list/map of "postal areas" and each "postal area" has a list of POIs, locations etc... There is also always a special "postal area" "", which contains all data we cannot match to a postal code. This way adding postal codes to the index does not increase the index much. In the worst case (performance) we only need to match postal codes to regions to gain some performance.

**Comment by Framstag** [comment]
I'll start working on this during the Hackerweekend. We'll see, how far I get.

**Comment by Framstag** [comment]
Context is https://github.com/Framstag/libosmscout/issues/322

The importer now also parses the postal code if available. This information results in a new list of PostalArea below an AdminRegion. Locations are now grouped by postal area/code below the admin region. There is a special postal area with name "" in cases where there is no postal code detected. Addresses are always in one of the postal areas, locations can be in multiple areas.

The reverse lookup and the locations search result will now include the postal area/code if available.

It is now also possible to search for a postal code, too. Postal codes though either match exactly or not at all.

The command line splitting/parsing code for search though does not support postal areas/codes.

What is missing?
* Testing, testing and further testing. This was a major change, thing could have get broken.
* There is no evaluation of postal area boundaries. To improve the rate of detected postal code, in a next step one could build up postal code areas by merging boundaries and check for "geometric inclusion" for addresses missing the postal code.

**Comment by Framstag** [comment]
Added some improvements to the LocationForm search. Now PostalArea is also evaluated.

**Comment by aquiles2k** [comment]
Could you elaborate please :) I see something about partial postal code mapping. Is there something else?

**Comment by Framstag** [comment]
For the location form search (but not for the string search and not for the POI form search) I now improved the search to also evaluate the postal area search criteria. If no postal area is passed this matches against all postal areas below the already matched region.

The code should now be more or less there to do similar for the two other searches (we just need to migrate the searches to the new code pattern).

Since the semantics of the searches now get complicated I however decided to just stop here and invest some time into creating infrastructure for tests.

As such I designed a new DSL ("OLT") that allows you to define a location index instance, modify the import so that a *.olt files can get imported and make the import synthesize the required objects to result in the given location index instance in result of the import and finally write a LocationLookupTest that creates a database based on the *.olt file by calling the importer programatically and make search calls against this database to validate the index and the search semantics.

Everything is already in place (at least in proof of concept quality) thanks t the hacking weekend, but the actual "synthesize" is missing. I hope to have some time to finish this part, too.

If it is working it would allow you and @Karry to define the required search semantics based on the required application behaviour and get me to implement it correctly until tests are green ;-)

**Comment by Framstag** [comment]
Nevertheless you can of course already start to tests the postal code search in the location form search...

**Comment by Karry** [comment]
Hi Tim. DSL that allow us to customise search index sounds interesting, but I am not sure if I fully understand it :-) How it will works technically? It will allow us to add all language variants for objects? Strip diacritics for non-latin languages?

**Comment by Framstag** [comment]
NO, it is just a small DSL where you can define actual (test) content for the location index. Instead of importing an *.osm.pbf file you would then import a locationtest.olt. A special call back would use the DSL parser to read the location index sturcture of the test file and would generate nodes, ways and relations to fake data (in this case the geometric representation would of course be close to nonsense and a map rendered on top of such import would result in strange result).

Thè structure of the locationtest.olt file would look liek:

```
REGION "Test"
  ALIAS "testy"
  LOCATION "street1"
    ADDRESS "1a"
    ADDRESS "2a"
  LOCATION "street2"
```

The actual DSL syntax is a little bit more complex, but I hope you get the idea. The idea is allow tests for the complete location index traversal and search code without managing a *.osm file with test data manually.

**Comment by aquiles2k** [comment]
That sounds very interesting! Please try to consider multi db search as the normal single db search works pretty well but as soon as multiple dbs are involved some new search challenges appear (like searching in a specific country or reverse geocoding on db borders). Does this DSL has support for POIs and Postal Codes, Ways and Crossings?

**Comment by Framstag** [comment]
Currently I plan to generate a administrate boundary and or place region for every hierarchical region. I woul dlike to make it simple. So if your region has 10 sub regions I will likely create a rwctangle and divide it into 10 sub rectangles, one for each sub region. For every way I would likely just generate a two node way (all left to right), from top to bottom of the region rectangle. For every address I would create a building on top (or below) the way. For POIs I would do something similar. For postal codes every address would have a corresponding tag.

I do not plan to implement any geometric specialties. I just create enough data so that the location index matches.

I also have ideas for other similar DSL that alow you to create test data to test routing. Such DSL would surely look different.

**Comment by Framstag** [comment]
Regarding multi-db: This should be transparent for the feature. It is up to the actual test to do multiple imports and read back the databases. so, yes this should be possible.

**Comment by Framstag** [comment]
I have now pushed a subset of the code (the actual test is missing, since it is currently red)

Here would be an example file fo an *.olt definition:

```
OLT
  OBJECT BOUNDARY 4 "Nordrhein-Westfalen"
    ALIAS "NRW" {

    REGION "Regierungsbezirk Düsseldorf" {
      CITY "Düsseldorf"
    }

    REGION "Regierungsbezirk Köln" {
      CITY "Köln"
    }

    OBJECT BOUNDARY 5 "Regierungsbezirk Arnsberg" {
      CITY "Dortmund" {
        SUBURB NODE "Brechten" {
          POSTAL_AREA "44339"
            LOCATION "Am Birkenbaum"
              ADDRESS "1"
              ADDRESS "2"
            LOCATION "In den Hüchten"
              ADDRESS "1"
              ADDRESS "2"
          POSTAL_AREA
            LOCATION "In den Hüchten"
              ADDRESS "3"
        }

        SUBURB NODE "Eving" {
          POSTAL_AREA "44339"
            LOCATION "Bahnhofstraße"
              ADDRESS "50a"
              ADDRESS "50b"
        }
      }

      COUNTY BOUNDARY 6 "Kreis Unna" {
        CITY "Kamen" {

        }

        CITY "Bergkamen" {
          SUBURB NODE "Heil"
          SUBURB NODE "Oberaden"
          SUBURB NODE "Overberge"
        }
      }
    }
  }
END
```

The ```PreprocessOLT``` code needs some further improvement to correctly map the content of the OLT file to some fake nodes and ways, but the current code at least show in which direction it should go.

**Comment by Framstag** [comment]
@aquiles2k: What is missing to close this issue? I repeatedly worked on this and improved the code. But I'm unsure if something is still missing? Did you do some tests? Are there any test case missing (now that we have the DSL and some simple test cases)?

**Comment by aquiles2k** [comment]
Hi, sorry for not coming back to this earlier. A collegue is currently in charge of the corresponding project and ive been busy with other things and just can occasionally work on this. 

We are currently in testing phase, so there might come some more real live search problems found but so far everything seems to be pleasing :) I'm closing this now as the general feature has been more then implemented by you. Thanks! All future nitpicks can go into there own issue.

Dont forget to claim the bounty :)
