### ISSUE TITLE
WaterIndex should detect and ignore usages of coastlines on land

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#355]
Water index generator highly depends on the fact that coastlines are "correct". For that reason, it filter out (smaller) islands that are intersecting with another islands or land (another coastlines in general).
But when island is placed on land completely (no intersection) it is keep and it may cause problems, like flood in city. 

This error may be created by mappers, and it should be fixed (see [changeset #47497330](http://www.openstreetmap.org/changeset/47497330#map=15/61.0107/24.4589), [changeset #47527790](http://www.openstreetmap.org/changeset/47527790#map=16/40.5187/19.3964)). But it may be created by coastline optimisation for low zoom, directly in generator! One example of this bug was found by @vyskocil in LA...

![coastlines-on-land-1](https://cloud.githubusercontent.com/assets/309458/26752367/7b2a0fbc-484e-11e7-9e77-0f0a5aaff0cb.png)

![coastlines-on-land-2](https://cloud.githubusercontent.com/assets/309458/26752369/80f46654-484e-11e7-97d6-556db3e541e0.png)

**Comment by aquiles2k** [comment]
I found a bug in netherlands too, might be the same issue? Theres a huge bay in netherlands which depending on zoom level doesnt get drawn. See attached screenshot and this google maps link for reference. I used current netherlands geofabrik download with bounding poly.

https://www.google.de/maps/@52.834205,5.419442,9.33z

![netherlands](https://user-images.githubusercontent.com/6095108/26837494-d3faa4bc-4add-11e7-9217-b151e8954aeb.png)

**Comment by Karry** [comment]
Hi. These areas near Amsterdam are not sea (in OSM), but lakes with `natural=water` - [Markermeer](http://www.openstreetmap.org/relation/49368#map=10/52.6868/5.3277), [IJsselmeer](http://www.openstreetmap.org/relation/945096#map=10/52.8111/5.3819). It is bug, because these lakes should be visible from zoom level 5 (with standard.oss), but it is not related with water index...

**Comment by Framstag** [comment]
If I remember correctly, I at least twice had the fun to flood parts of the netherlands :-) I'm not sure, if it is the same "lake" but the last problem as far as I remember had to do to do with a small street (Dam) crossing the lake. This made the land/sea tile detection go amok. I do not remember how I fixed that. AFAIK we drop bridges and tunnels but in that case it was neither bridge nor tunnel nor did the dam had a coastline. I'm looking at missing borderlines in austria and germany first. So if you are missing some fun...here you can get it :-/

**Comment by Framstag** [comment]
Netherlands fail on zoom level 7 because of (some tiles in that "should be water" part):
* Assume land: 63,34 Way T highway_unclassified is defining area as land
* Assume land: 64,34 Way 48617396 highway_service is defining area as land
* Assume land: 64,34 Way 48617396 highway_service is defining area as land
* Assume land: 64,37 Way 51967953 highway_service is defining area as land

Hmm, why does this work at all? Similar regions have also type "land" for different zoomlevel.

So, technical the water index is right. Sea is only where there are coastlines. An `natural=water` is just a huge amount of water *on land*. So what happens? The painter first draw the land tiles. After that areas are drawn on top, sorted by bounding boxes (see `AreaSorter` for details). So the "lake" should get drawn on top. If there are island in the lake, they will be drawn on top of the lake, because of their bounding box being smaller. Ways are drawn later on top of areas.

So the question is: Why is the water not visible? Is it not drawn at all? Let's see...

**Comment by Framstag** [comment]
OK, the natural=water is not rendered because an optimized shape for the water is fetched for this zoom level, but the index generator for this dropped the area (in error). Let`s see, how I can fix this.

**Comment by Framstag** [comment]
OK, the natural=water is not rendered because an optimized shape for the water is fetched for this zoom level, but the index generator for this dropped the area (in error). Pushed fix for that problem. So after saving the Netherlands, L.A. is still in need of help ;-)

**Comment by vyskocil** [comment]
I just built california.osm.pbf from geofabrik and this patch seems to also fix the flooding of L.A !
You might close this issue :-)
