### ISSUE TITLE
RoutingService crash when last two routing paths are restricted for vehicle

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#402]
Hi Tim. 

I found bug in `RoutingService`. Where some path is restricted for current routing vehicle, target routing node is added to `openList` with access flag set to false. Computation then continue but such node may not be added to `closedSet` (accessViolation=true). Next route node (restricted too) may be the target, but computation cycle ends and route chain is build in `ResolveRNodeChainToList`. This method fails on `assert(prev!=closedSet.end());`, because previous restricted node don't exists in `closedSet`. 

You can reproduce this bug with Austria database:
```
./Demos/Routing \
    ~/Maps/europe-austria-20170627-221026  \
    48.0248609075286 16.299005468043976 \
    48.19794298919518 16.430359691692868```
```

I don't understand why routing node is added to `openList` when it is restricted...? Or why can routing stops on node with `access==false`?

Computation log:
```
Analysing follower of node 69011029 (Way 315462255[3757230653776527361]) 3.07833 0.000401124 3.07873
  Skipping route to 69011106 (Way 314381119) => moving from non-accessible way back to accessible way
  Skipping route to 69010820 (Way 315461078) => moving from non-accessible way back to accessible way
  Skipping route to 68909481 (Way 315462255) => back to the last node visited
  Inserting route to 69020717 (Way 315462255) 3.07922 0 3.07922 3757230653776527361
....

Analysing follower of node 69020717 (Way 315462255[3757230658050216961]) 3.07922 0 3.07922
  Skipping route to 69010953 (Way 315462120) => moving from non-accessible way back to accessible way
  Skipping route to 69011029 (Way 315462255) => back to the last node visited
  Inserting route to 69028555 (Way 315462255) 3.08022 0.000455393 3.08067 3757230658050216961
  Skipping route to 69020791 (Way 315462576) => moving from non-accessible way back to accessible way
Reached target: 69020717 == 69020717 (forward)
```

**Comment by Karry** [comment]
Hmm, how is possible that this path have both flags? `RouteNode::usableByCar` and `restrictedForCar`?

**Comment by Framstag** [comment]
Restricted access means, one can enter a region of restricted access but one cannot leave it again. There are corner cases where a node is connected to an restricted and a unrestricted way. If the router first visits the resticted way it cannot remove the node from the open list because in this case the alternative unrestricted way via the node would not be evaluated anymore. I tried to fix this by readding the node to the open list again.

**Comment by Karry** [comment]
I am confused even more now :-) Can you give me example from real world or link to OSM wiki where is described what ways can have such "restriction"?

**Comment by Framstag** [comment]
I'm speaking about why a route nod eis added to the openlist again. And I'm especially talking about access=destination (see https://wiki.openstreetmap.org/wiki/Key:access).

As you can see from AccessRestrictedFeature::Parse() access:dstination (and other values) (should) trigger an entry into the access bitset as "restricted" for the given vehicle.

In such case you must only drive into an area (defined by the hull of ways with above access value) if your destination is within the area. Else it is not allowed to take such way.

For the router this means, you can use ways with above access value but after you are on such way you must not take a way without the this access value.

There are situations though where a routing node lies on the border of the (virtual) area. That means it is connected with a way through the area but also with a way around the area (you would take if your destination is not within the area).

Now you visit a restricted way first and there is no shorter way by algorithm so the routing node is "closed". But it must not be closed because in result if you later probe the way around the restricted area but with the routing node on the border you not take this route because the relevant "border" routing node is just not "open" anymore.

In result the router would take a far longer way or would just not find a way at all.

Concrete example I tested for fixing above problem:

See the following ways:
* https://www.openstreetmap.org/way/28811002 (Voßkuhle)
* https://www.openstreetmap.org/way/25606997 (Thomas-Mann Straße)
* https://www.openstreetmap.org/way/26841511 (Im Defdahl)
* https://www.openstreetmap.org/way/53256817 (Target way)

Thomas-Mann Straße has vehicle=destination.

The original router was not able to drive you from Voßkuhle via Defdahl to the target road (which is also Defdahl), because of the crossing of Thomas-Mann Straße with Defdahl for above situation.

There is possibly another fix for this, but the I hope the reason that lead to my fix is now more obvious.

**Comment by Framstag** [comment]
Regarding have set s? RouteNode::usableByCar and restrictedForCar:

I hope this is already clear after my previous explanation? You can also check the description of the corresponding TypeFeatures.

In this case it means:
* usableByCar: A car can travel of this way.
* restrictedForCar: Though it can travel, the access is restricted. So the router must make sure, that the route does not leave the restricted area, else it would be an forbidden passing of an restricted area.

In principle in OSm it is possible to encode even more complicated access restrictions. These would depend on the role of the vehicle or for example on the actual hour. This is not implemented yet, because of the following conflict:

To make routing fast the routing graph should be small on disk an in memory. The routing should also have high locality on disk and in memory to make sure we have optimal IO and CPU usage (CPU cache usage). Adding more on more and more complex data to the graph would go against this (and would duplicate data to some extend). The initial router in fact loaded the actual way data. This was more powerful but much slower. I'm not yet sure how to handle this. We currently thus do not support simple gates and similar. For gates I'm thinking of creating route nodes for them and add fake turn restriction or similar to handle the gate. For time based conditions we finally possibly have to store an optional file offset to point for additional special case data, making things small only for this node.

It would also be interesting to load route nodes in one go for a complete (small) tile. Such bulk loading may in fact be faster than the current scatter load. Instead of raw file offsets we would split them into a tile id and an relative file offset into the tile data.

**Comment by Karry** [comment]
Thank you. It is clear now. I will prepare fix in https://github.com/Framstag/libosmscout/pull/399

**Comment by Karry** [comment]
Hi. We need to solve one question: When we have junction with two roads with "motor_vehicle=destination" and another two roads without restriction, it is legal to ride directly like Mapzen router suggest or it is necessary to ride around as GraphHopper suggest?

Mapzen:
![route-access-destination2](https://user-images.githubusercontent.com/309458/28237751-dec2a6d8-6946-11e7-937b-8a3511fdfe1e.png)
GraphHopper:
![route-access-destination1](https://user-images.githubusercontent.com/309458/28237772-1597c242-6947-11e7-8cb4-c11a399f963c.png)


http://www.openstreetmap.org/directions?engine=mapzen_car&route=52.48390%2C13.33389%3B52.48681%2C13.33316#map=17/52.48559/13.33490

**Comment by Karry** [comment]
Hi. I solved this by defining two different sets of closed nodes https://github.com/Framstag/libosmscout/pull/399 because one route-node may be accessible from two different ways and it depends on future computation what may be used (if target is restricted or not)...

```
    // Restricted way (access=destination) is a way that may be used just
    // in case when target is on this way. Some routing nodes may be accessed
    // from two different ways - one without any access restriction (closedSet)
    // and second with restriction (closedRestrictedSet)
    ClosedSet                closedSet;
    ClosedSet                closedRestrictedSet;
```
...closing
