### ISSUE TITLE
Is there any simple/built-in way to draw custom points/paths on map? [$50]

### ISSUE THREAD

**Issue by hexonxons** [Framstag/libosmscout#405]
I want to draw paths and points with bearing over qt map, but I couldn't find any api to do that.
Right now I'm drawing it using `QPainter` in custom `MapWidget` overloaded class, but there are a lot of different calculations to handle map scrolling/zooming. It works, but I wonder if there are any public apis to draw points and paths by its lat/lon coordinates with already implemented zoom/scroll calculations.
![2017-07-10-121340_3840x1080_scrot](https://user-images.githubusercontent.com/663637/28011273-72e187a2-656a-11e7-871f-ede6f93e153c.png)

**Comment by Karry** [comment]
Hi. Such api don't exists now. We don't support even route rendering, I removed it when I was adding support for rendering multiple databases... But it would be great to have it! Map rendering library without custom objects on the map is not so useful :-/

Question is how do it
 - extend (tiled, plane) `MapRenderer` and render custom objects with `MapPainterQt`. Style of custom objects may be customised by map stylesheet, object labels may be taken into account during label placing...
 - create some abstract overlay renderer that will be "injected" into `OSMScoutQt` and called from `MapWidget` after `MapRenderer`? It may be useful for custom heatmap, hill shading...

I plan to work on it, but I have no schedule. It may takes me months or years... Merge requests are always welcome ;-)

**Comment by Framstag** [comment]
The problem Lukas mentiones is a problem of the libopsmscout-qt-client library. This library implements many feature above the basic libosmscout libraries for QWt based backends. It also allows drawing local maps and can downloads tiles, too.

The various render backends do allow to inject custom objects using the poiXXX attributes in the MapData structure. In this case the poiXXX attributes will not be touched by the MapService and they will be rendered by the backend as normal objects.

See http://libosmscout.sourceforge.net/tutorials/renderonmap/ for more details.

This above trick is not support my libomscout-qt-client yet, because you cannot simply use the normal Qt backend if you want to render on top of downloaded tiles.

It should be still possible though but would require some additional handling. You can configure the Qt backend to do not draw any backgrounds. So mentioned overlay can possible simulated by an additional Qt MapPainter with matching configuration.

**Comment by Framstag** [comment]
@Karry: Can this now get closed?

**Comment by Framstag** [comment]
IMHO it is now possible to draw routing result on top of the map. At least I have seen this in the Sailfish routing app developed by Karry. Looks like this only needs some documentation? It is possible that Karry is in Holiday, so we might have to wait for his answer.

**Comment by Karry** [comment]
Hi.

Yes, it is now possible to draw custom ways on Qt's map, but I understand that this is not enough for some usecases. I can imagine few overlays that are not simple to implement now:
 - hill shading (tile based overlay) 
 - precipitation animation (like [radareu.cz](http://www.radareu.cz/))

For that reason, I want to create simple way how to add custom overlay canvas for map component... But be patient, my time is limited.

**Comment by Framstag** [comment]
@Karry: Any change of status on this?

**Comment by Karry** [comment]
There is QML component for tiled overlay, that I am using for hill shades in my app (in combination with tile downloader). It may be used as inspiration for someone who needs to create custom overlay with separate drawing thread. Its superclass may be used for creating even simpler overlay with drawing in context of UI thread...

I am closing this issue. If there is something that is missing for you, let us know.

**Comment by hexonxons** [comment]
@Karry Thank you, but we switched from osmscout to mapviz in our debugging env, so I cant check if I am able to draw paths via overlay. I have just checked PR and it seems it works.
Don't forget to claim ur bounty)
