### ISSUE TITLE
CMakeList changes don't allow to build without import library

### ISSUE THREAD

**Issue by rinigus** [Framstag/libosmscout#415]
It looks like commit 221d9f1760079eb30453ba09f687cde28929d2df broke CMakeList in a way that does not allow to build the library without import library. Earlier, I could specify `-DOSMSCOUT_BUILD_IMPORT=OFF` as an argument to cmake. Right now, its not checked and `add_subdirectory(libosmscout-import)` is executed unconditionally

**Comment by Framstag** [comment]
Which library does not build with the import library anymore? Do you mean withthe first "library" the set complete buikd alias the set of all libraries?

libosmscout-import and the Importer can always be build. The dependencies on libxml and protobuf are optional. Because I wanted the central build to cover as much sources as possible I thus changed the cmake file in this regard, so that the import-library and the importer are build, even if the optional dependencies are not fulfilled. Yes, the resulting importer though may in result not be of much help if both dependencies are missing.

If I accidently broke the option to stop building the import library unconditionally than this was not intended (I'm no cmake wizard) and should be fixed. A pull request would be nice :-)

**Comment by rinigus** [comment]
Re cmake wizard: that makes two of us :)

I think that protobuf on SFOS is older than the one used to generate the protobuf-headers. As a result, its not so easy to build libosmscout-import and Importer. However, since they are not really needed, I was just disabling them during the build by specifying 

OSMSCOUT_BUILD_IMPORT=OFF

In the new version of CMakeList, this variable is not checked anymore and just set to OFF, if I read the config correctly.

I wonder whether we have anyone who is cmake wizard? I can try to make PR, let's hope it will not break anything else.
