### ISSUE TITLE
Change GetClosestRoutableNode() and CalculateRoute() API

### ISSUE THREAD

**Issue by Framstag** [Framstag/libosmscout#442]
See #440. GetClostestRoutableNode() should not return an id of a node, but it should but a "abstract" point on the closest routable way. CalculateRoute() API should be changed to get such a location description passed. Internally it again looks for the closest routing node in each direction on the way in relation to the given position.

**Comment by vyskocil** [comment]
Maybe SearchClosestSegment() from [Navigation.h](https://github.com/Framstag/libosmscout/blob/master/libosmscout/include/osmscout/Navigation.h) would be helpful ?

**Comment by vyskocil** [comment]
I looked at the code, particularly on `RoutePosition SimpleRoutingService::GetClosestRoutableNode()` and I think that maybe localized changes to this method would be enough, letting the `CalculateRoute()` API unchanged.
Changing the code that calculate the minimum distance to look at the orthogonal distance from the source point to the segment [node_i, node_i+1] for all nodes in the selected ways instead of computing the minimum distance from the source point to node_i for all i. I mean replacing this code : 
```
      for (size_t i=0;  i<way->nodes.size(); i++) {
        double distance=sqrt((way->nodes[i].GetLat()-coord.GetLat())*(way->nodes[i].GetLat()-coord.GetLat())+
                             (way->nodes[i].GetLon()-coord.GetLon())*(way->nodes[i].GetLon()-coord.GetLon()));
        if (distance<minDistance) {
          minDistance=distance;

          position=RoutePosition(way->GetObjectFileRef(),i,/*database*/0);
        }
      }
```

and use 
 ```
 /**
   * return the minimum distance from the point p to the line segment [p1,p2]
   * this could be the distance from p to p1 or to p2 if q the orthogonal projection of p
   * on the line supporting the segment is outside [p1,p2]
   * r is the abscissa of q on the line, 0 <= r <= 1 if q is between p1 and p2.
   */
  double DistanceToSegment(double px, double py,
                           double p1x, double p1y,
                           double p2x, double p2y,
                           double& r,
                           double& qx, double& qy)
```
from Geometry.cpp for each two consecutive nodes on the way, and if this distance is lower than minDistance select the closest node of the two using r, node_i if r<0.5, node_i+1 otherwise.

What do you think about that ?

**Comment by Framstag** [comment]
So you mean, you first find the routable way that is closest by finding the smallest orthogonal line through point and way candidates? And then - if you found the closest way  - find the closest routing node on this way.

That sounds like an improvement and is definitely worth a try.

**Comment by vyskocil** [comment]
I made a pull request with the changes to use DistanceToSegment(), this seems to improve the starting and destination node searching in the case of sparse ways (like straight motorway for example where the starting node was often picked on the small roads on the side)

**Comment by Framstag** [comment]
Is the current state after the pull request of @vyskocil good enough, so that we can close the issue, or would there still be an improvement in changing the API?

**Comment by Framstag** [comment]
Closing. Please create a new issue, if one  need further improvement.
