### ISSUE TITLE
areaWayIndex->GetOffsets() returns too many ways outside the bounding box

### ISSUE THREAD

**Issue by vyskocil** [Framstag/libosmscout#452]
In SimpleRoutingService::GetClosestRoutableNode(), the method call areaWayIndex->GetOffsets(boundingBox,wayRoutableTypes,  wayWayOffsets, wayLoadedTypes) return many ways outside the bounding box, in my example I choose radius=50m and got this bounding box : 

<img width="436" alt="screen shot 2017-08-22 at 14 08 35" src="https://user-images.githubusercontent.com/452704/29564776-7b2b6bf8-8743-11e7-9c78-3861deeee232.png">

the method returns 1278 way offsets and some are more than 10 km from the starting point (lat=43.583556141960877, lon=7.0234730154158056)

**Comment by Framstag** [comment]
The AreaWayIndex, which resolves ways based on the given bounding box usies a bitmap approach. That means, for every type there is a bitmap consisting of tiles, where for each tile a list of objects in this tile is stored.

The zoom level of the tile (which in turn defines it size on the ground) is calculated depending on the distribution and count of objects for the given type. See `AreaWayIndexGenerator::FitsIndexCriteria()` for details. See also the output of Step#16 during import that dumps the zoom level chosen for each type. Also see the implementation for AreaWayIndex. On my system for my region highway_motorway has zoom level 11. 

The index is optimized (at least we try) that there are not too many empty tiles but also not tiles with too much data. Data storage is defined as optimized, if the zoom level is as small as possible (smaller bitmap) but has enough granularity that the number of objects returns is not too big.

Since a motorway type has not that many instances, this results in rather big tiles containing objects of a big region. So you might get objects way out of the given bounding box since the tiles themselfs has a much less resolution. You have to postprocess and filter by distance the results form the index if you require accurate data.

Tests have shown that using tries or similar structures result in better granularity but need much more disk space since there is a rather big overhead because of administrative data in the on-disk structure.

A trie structure would possibly only be better for very sparse distributed object types with high locality but also high count at that places. It would be possible to use different index structures for different types.

**Comment by vyskocil** [comment]
Ok, I understand, thanks for the explanations !
