### ISSUE TITLE
iOS: High zoom-level sometimes rendering slow

### ISSUE THREAD

**Issue by larsmango** [Framstag/libosmscout#465]
I noticed that areas with high density elements (e.g. lots of streets/buildings) are very slow for rendering at high zoom levels. Some areas with lots of buildings sometimes take up to 30 seconds to render all times for one screen.
Is there any dispatch_queue that is being used with a low priority for rendering? I noticed that the `NSThread` that does the rendering has a `.threadPriority` of `0.5`. I think `1.0`would be the maximum.

**Comment by Framstag** [comment]
In general the renderer is not that slow with the default style sheet. I do remember though, that the integration intot he iOS map stack resulted in some queueing within the stack that resulted in such effect. I hope @vyskocil can say something about that?

**Comment by vyskocil** [comment]
The demo app use the MkMapView component from Apple UIKit, libosmscout provide rendererd image tiles at the component request for given coordinates and zoom level according to the user actions : scrolling, zooming, rotating,.... These render requests are queued in a NSOperationQueue and dispatched on the available CPU core(s) (2). If the user pan and zoom the too quickly the requests floods the queue and we render tiles that are not any more on screen before the visible ones... The situation is even worse because MkMapView request rendering of tiles with (zoom-level - 2) to have a preview at lower resolution of a given location and I found it also has his own throttling algorithm interfering with things we could try in our side. For exemple I tried to re-order requests in the queue prioritizing the tiles with the current zoom level, but the component blocks on waiting for lower zoom tiles for preview, etc...
The solution is maybe to develop our own tiling component (hard to mimic the Apple one and it is very extensive as it handle overlays that move with the map, and many other things...)
Or maybe the good solution is to adapt the OpenGL drivers !

**Comment by Framstag** [comment]
Note that the qt-client-library already contains a stack for rendering. This of course Qt specific and depended in some parts, but possibly much of it could be used in a similar way under Mac, too.

**Comment by larsmango** [comment]
I would like to keep the MKMapView approach for iOS. It is too good to change it (smooth user experience, MKMapAnnotations, Overlays, etc...). 
So as far as I understood from @vyskocil's comment the problem is the order in which MKMapView requests tiles?
Do we get any kind of callback for tiles that are not required anymore so we could remove them from the NSOperationQueue?
In general, does it help to remove fine details from the map (e.g. house bonding boxes) to improve rendering speed? I've noticed that the rendering is much quicker on lower zoom levels when not that many items are visible.

**Comment by Framstag** [comment]
Reducing details will speed up loading time for tile data and also tile rendering time. 

If you want to render using multiple parallel threads you have to create multiple instances of some parts of the libosmscout render stack, too. Especially the MapPainter itself is not thread safe in general. We have spoke of parallelizing the rendering, but I'm not sure if @vyskocil  or @Karry  have actually tested it. Nevertheless it should be possible but would require more resources (memory).

Regarding details of the MPMapView and options @vyskocil  is the expert :-)

**Comment by Framstag** [comment]
@larsmango: How should be continue with this issue? Do you need further help? Can we close the issue?

**Comment by larsmango** [comment]
@Framstag sorry for the late reply. Do you already have an issue tracking the possible implementation of parallel rendering of tiles for iOS? I think this would be a major improvement for rendering speed.

**Comment by Framstag** [comment]
No there is no such issue yet, you can create one of course, since such thing might may sense in some situations. I personally have not yet invested in it (besides constant lack of time ;-)), since I assumed that on mobile there might not be enough resources (CPU,memory) to make use of such approach .

In principle the solution will be to instantiate a MapPainter instance for each thread (in a thread pool). It will also be interesting if the current asynch/lock code in the MapService is enough to make use of it in multiple threads.

**Comment by Framstag** [comment]
Please add explicit issues for the part of the discussion that are still important for you.
