### ISSUE TITLE
`make full` fail due to 'agg2/agg_font_freetype.h' file not found

### ISSUE THREAD

**Issue by ayeteng** [Framstag/libosmscout#484]
Below is what I did on my OSX.

> git clone https://github.com/Framstag/libosmscout.git
> cd libosmscout
> . setupAutoconf.sh
> make full

and I get the error message:

Making all in src
  CXX      osmscout/MapPainterAgg.lo
In file included from osmscout/MapPainterAgg.cpp:20:
../include/osmscout/MapPainterAgg.h:36:10: fatal error: 'agg2/agg_font_freetype.h' file not found
#include <agg2/agg_font_freetype.h>
         ^
1 error generated.

> brew install libagg
Warning: libagg 2.5 is already installed

use homebrew to install the libagg but I cannot locate this agg_font_freetype.h. Did I missing anything here?

**Comment by Framstag** [comment]
I remember to had this issue, too. The configure script for the agg backend should tests, if font support via freetype is enabled/available for agg but based on your error message, it seems, it does not do this correctly.

libagg has in principle freetype support. Under Arch Linux I use:

https://www.archlinux.org/packages/community/x86_64/agg/ and as you can see from the package dependencies and the file list the header is there. It looks like homebrew decided to build libagg without freetype support. I cannot do anything about this (but fix the configure file). You could try to build agg with freetype enabled on your own.

There is a native iOSX backend. Do you really need agg under Mac OS?

Since I have a Mac Book, I'll see, if I at least get the build to not fail in above case.

**Comment by Framstag** [comment]
Note, that autoconf support on OS X and in general is deprecated (but still working in principle). I suggest to take a look at the cmake based build (the meson build does not correctly support building of framework libs and XCode projects due to upstream errors). The cmake support is not perfect yet, @vyskocil  is still working on it and we are yet lacking in deep documentation. But if you have some experience in cmake, he likely is happy to get help :-)

**Comment by Framstag** [comment]
I tried to apply a quick fix, lets see if this improves the situation. Note that you have to delete libosmscout-map-agg/Makefile, because that is the trigger for building it.

**Comment by ayeteng** [comment]
The quick fix works.
Thanks Framstag!
