### ISSUE TITLE
CMake build Sample DrawMapOpenGL is missing

### ISSUE THREAD

**Issue by DerKleinePunk** [Framstag/libosmscout#497]
if(${OSMSCOUT_BUILD_MAP_OPENGL})
	add_executable(DrawMapOpenGL src/DrawMapOpenGL.cpp)
	set_property(TARGET DrawMapOpenGL PROPERTY CXX_STANDARD 11)
	target_include_directories(DrawMapSVG PRIVATE ${OSMSCOUT_BASE_DIR_SOURCE}/libosmscout/include ${OSMSCOUT_BASE_DIR_SOURCE}/libosmscout-map/include ${OSMSCOUT_BASE_DIR_SOURCE}/libosmscout-map-opengl/include)
	if(APPLE)
	  target_link_libraries(DrawMapOpenGL OSMScout OSMScoutMap OSMScoutMapOPENGL)
	else()
	  target_link_libraries(DrawMapOpenGL osmscout osmscout_map osmscout_map_opengl)
	endif()
	install(TARGETS DrawMapOpenGL RUNTIME DESTINATION bin LIBRARY DESTINATION lib ARCHIVE DESTINATION lib)
else()
	message("Skip DrawMapOpenGL demo, libosmscout-map-gl is missing.")
endif()

DrawMapOpenGL.cpp:29:10: fatal error: config.h: No such file or directory
 #include "config.h"

**Comment by Karry** [comment]
When I was trying to make DrawMapOpenGL demo work, I got the feeling that this demo is deprecated and we should remove it. It is using GLUT instead of GLFW in OSMScoutOpenGL and require to do many changes to make it compilable... @Framstag @fannymonori do we want to maintain both? DrawMapOpenGL in demo and OSMScoutOpenGL as example application?

**Comment by Framstag** [comment]
The OpenGL demo in the Demos sub directory should be deleted. It was a early proof on concept of mine. It showed that it is possible. But the solution is by far inferior in any means to the solution of @fannymonori . There is no need to keep it. I can delete it.

**Comment by Framstag** [comment]
Deleted and changes pushed.
