### ISSUE TITLE
Logger usage after free

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#514]
Hi. I am seeing weird behaviour on arm (but I guess that similar situation may happen on x86). When main thread exits, `__cxa_finalize` symbol is called in main thread context and it calls `osmscout::Log` destructor (static variable). But other threads are still alive and sometimes call some log functions like `log.Debug()`. This situation creates `SIGSEGV` error, because `Log` is used after destruction. It is not big issue, only difference is that application ends with non-zero exit code ;-) But I can imagine that I will need proper shutdown in the future. Is here some way to guarantee that `Log` destructor will be called when other threads ends?

**Comment by Framstag** [comment]
See also https://stackoverflow.com/questions/469597/destruction-order-of-static-objects-in-c

libosmscout tries hard to avoid the use of global object for the following reason:
* Initialization/deinitialisation order
* Multi-instancability

IMHO freeing of resources should be always "under control", even on system where the OS will do cleanup on application exit. Reference to ressources should either be handled via RAII or reference counting. Since C++ does not has a "good" deinitialization order for global objects especially reference counting is a ways to ensure that deinitialisation has some controlled order in this case.

Logging may in fact be one of the rare exclusions, where global objects make sense (because of performance reasons and ease of use for example) because it does not really claim resources (normally, exception, too, if you explicitly log to self-created files)) . Reference counting could be used, too, but likely will not make a good API.

If you have threads that are still running while destruction of global objects is already started, that is IMHO a bug in the application and you should make sure that all threads are finished before main() has exited. Why are there still threads and resources after main() has finished? Can this be fixed?

**Comment by Karry** [comment]
I discuss this problem with my colleague who has better c++ knowledge. This problem dont exists on Windows, this OS terminates all threads after return from `main` method and call destructors of static variables then. But on linux, QML engine thread is still alive and MapWidget destructor (and d-tors of data models created from QML)  is called after destructor of static variables (Log).
