### ISSUE TITLE
iOS device Running issue.

### ISSUE THREAD

**Issue by topdeveloper0017** [Framstag/libosmscout#577]
![screen shot 2018-03-11 at 11 18 17 pm](https://user-images.githubusercontent.com/21339276/37259109-943efadc-2582-11e8-9f88-d1df2ee5491d.png)

I am getting many issues when I try to run library in iOS device.
How would I fix these issues ?

XCode is 9.2, iOS version is 11.2.5

**Comment by vyskocil** [comment]
These issues seems to be the result of a badly configured build wherer SSE instructions are enabled on iOS target. How are you building the osmscout libs ?

**Comment by topdeveloper0017** [comment]
I can run the code on iOS simulator, but cannot run the code on real device.

**Comment by vyskocil** [comment]
Yes because the simulator is running on the Mac processor which is a Intel one that has SSE instruction set but not the real device !

**Comment by topdeveloper0017** [comment]
so is there any way to run the code on real device ?

**Comment by vyskocil** [comment]
You have to use CMake build system

**Comment by topdeveloper0017** [comment]
I have built the code using meson, is that issue ?

**Comment by topdeveloper0017** [comment]
Meson building is issue ?

**Comment by Framstag** [comment]
The meson build was written by me. Meson current support for Mac OS/iOS is not good. It looks like they lack submitters for the OSs (See for example https://github.com/mesonbuild/meson/issues/1957). It is possibly that this has improved in the 0.44 or 0.45 release, but I nevertheless suggest to better use cmake instead of meson for Apple operating systems.

Note that we did not get cmake to build correct frameworks yet :-/ So even for the cmake and Mac OS/iOS combination we need help, too (See https://github.com/Framstag/libosmscout/issues/526).

**Comment by topdeveloper0017** [comment]
Hello, One question ?
How can I draw the routing between two locations in iOS app using your library ?

**Comment by Framstag** [comment]
See http://libosmscout.sourceforge.net/tutorials/renderonmap/ In this case I would suggest solution 1, the demo application should already work this way.

**Comment by Framstag** [comment]
@topdeveloper0017: Can we close the issue?

**Comment by Framstag** [comment]
Closing the issue.
