### ISSUE TITLE
"Where am I?" functionality. LocationService::DescribeLocation don't work for me

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#58]
Hi tim, I want to add "where am I?" functionality to OSMScout for Sailfish. I tried to use DescribeLocation demo, but it give me empty results. I want something like "you are in Czech Republic, Prague, near the street Biskupcova". Maybe something similar your described in feature request https://github.com/Framstag/libosmscout/issues/45

When I print found administrative regions in `LocationService.cpp:1264` it gives me some description where this position is, but why this information is not returned from `DescribeLocation` function?

    for (auto &adminRegion: adminRegionVisitor.adminRegions){
        AdminRegionRef regRef = adminRegion.second;
        std::cout << "admin region: " << regRef->name << std::endl;
    }
 
Am I looking for wrong function?

**Comment by Karry** [comment]
Or just ask differently. Can I change LocationService::DescribeLocation to fit my and https://github.com/Framstag/libosmscout/issues/45 requirements? Or should I create another function?

**Comment by Framstag** [comment]
The LocationDescription demo (I assume you mean that one :-)) uses the DescribeLocation method of the location service. This method is designed to return multiple description variants for the given geo location based on information from the database.

The LocationService allows the API to be extended internally by new description methods. Currently there are only two descriptions implemented.
* Description based on the geo location (this is 1:1 the input)
* In relation to a coordinate

The examples from the code comment:

```bash
$ src/LocationDescription ../maps/nordrhein-westfalen 51.57162 7.45882
Coordinate: 51.57162 N 7.45882 E
Is at address: In den Hüchten 29, Dortmund
```

```bash
$ src/LocationDescription ../maps/nordrhein-westfalen 51.57251 7.46506Coordinate: 51.57251 N 7.46506 E
7.6m S of address: Am Birkenbaum 6, Dortmund
```

Further implementations of location description are planed: See #43, #44, #45

I assume that in your case no address was found, because there is a limit regarding the  bounding box, the address is searched in:

```C++
    GeoBox           box100=GeoBox::BoxByCenterAndRadius(location,100);
```

The existing implementations are rather straight forward. So if you need another description this should be easy to add on your own.

There is should be no need for a new API, just extend the existing one by adding a new Description class.

**Comment by Framstag** [comment]
I have added a small "how to implement" comment on all three above mentioned issues, to describe a possible implementation.

**Comment by Karry** [comment]
Ok, I will try to extend current method. 

I probably found why `DescribeLocation` don't work in Prague and works well in Dortmund. On location 51.57162 7.45882 is building with these tags:

    addr:city=Dortmund
    addr:country=DE
    addr:housenumber=29
    addr:postcode=44339
    addr:street=In den Hüchten
    building=yes

But in Prague are addresses filled by different way. You can see it on location  50.09084 14.49769. Here is building (area) with tags:

    building:levels=6
    building=yes
    source=cuzk:km

and inside this area is point with address tags:

    addr:conscriptionnumber=2517
    addr:housenumber=2517/76
    addr:postcode=13000
    addr:street=Pod lipami
    addr:streetnumber=76
    source:addr=uir_adr
    uir_adr:ADRESA_KOD=21795134

I will try to modify `DescribeLocationByAddress` to accept both methods.

**Comment by Framstag** [comment]
Ah, OK. Could be the case, that I missed that one. If you have questions regarding the implementation/possible fix => ask!

**Comment by Karry** [comment]
Hi. It is possible that this address node don't exists in `location.idx` file? I extend `LocationService::DescribeLocationByAddress` by node lookup, but when I print all addresses in `LocationIndex::VisitLocationAddressEntries` I can't see this address. What conditions should be meet for nodes to be written to `location.idx`?

In `map.ost` is just:

    TYPE address
      = NODE AREA (EXISTS "addr:street" AND EXISTS "addr:housenumber")
        ADDRESS

**Comment by Framstag** [comment]
Note that the importer not only generates location.idx but also location*.txt. This should help to see what data gets index and how it was sorted into the hierarchical structure.

Normally the location index generator should be triggered by the ADDRESS attribute for the TYPE address (this is the flag to tell the importer that this type is likely addressable). (The required features for the address data should be automatically added by TypeConfig, if this option is set.)

I'll also take a look as soon as I have some time, if there is a general error in the handling of nodes of type address.

**Comment by Framstag** [comment]
OK; I have now identified the bug and pushed a fix to the github repository. A push to the sourceforge repository will follow.

**Comment by Karry** [comment]
Wow, it was fast. I repeated import from step 18, `location_full.txt` contains more entries now, but my home isn't in `nodeaddress.dat`...

**Comment by Framstag** [comment]
Strange. Please add some std::cout to SortNodeDat,cpp

```
  bool NodeLocationProcessorFilter::Process(Progress& progress,
                                            const FileOffset& offset,
                                            Node& node,
                                            bool& /*save*/)
```

to see, if your node is detected as address. You can use `DumpData -n <OSM node id>`to get the file offset of your node to identify it.

**Comment by Karry** [comment]
Oh, sorry, I used bad Import step. When I repeat Import completely, I see another additional addresses, but not mine... I will try to investigate why.

**Comment by Karry** [comment]
Ok, node is written to `nodeaddress.dat` correctly, but it is filtered out in Import step 21 with message:

    Street of address 'Pod lipami' '2517/76' of Node 2731849 cannot be resolved in region 'Žižkov'

[import-logs.zip](https://github.com/Framstag/libosmscout/files/348040/import-logs.zip)

debugging continue... :)

**Comment by Karry** [comment]
Oh. Many addresses in Prague (automatically imported from [uir-addr](http://forms.mpsv.cz/uir/) database) contains lowercase in second word (after preposition) in street name :-( "Pod lipami" is wrong, is should be "Pod Lipami"...

It should be fixed in OpenStreetMap database, not in OSM Scout library... What do you think?

**Comment by Framstag** [comment]
I'm not en expert in mapping regularities, but IMHO it always makes sense, if things follow a pattern - especially if you want matches.

Is there a local mapper mailing list. I would ask there...I haven't looked at the code yet, but in principle it should be possible to match without case. Though this will never be perfect, since stuff like toUppercase() is local sensitive and depending on your locale information available not as simple as it sound like (though it should work in your case).

**Comment by Karry** [comment]
Thanks Tim for help with this issue.
