### ISSUE TITLE
Is there a lookup POI demo with specific type?

### ISSUE THREAD

**Issue by jialinxie** [Framstag/libosmscout#618]
Hi, i am trying to add something on OSMScout2 demo, which can lookup poi with specific type, such as restaurant, cafe, ATM,etc.  I took a look at [osmscout-sailfish](https://github.com/Karry/osmscout-sailfish/blob/master/qml/pages/Search.qml), but it use qml and Sailfish sdk, and i didn't find out how to use NearPOIModel.
Can you give a simple demo or any idea ? Grateful for reply.

**Comment by Framstag** [comment]
There are multiple layers of code involved:
* The LookupPOI code should show you how to to use the service bases API of libosmscout itself
* The qt-client library wrapps this and maps it onto a model to supply the backend-code for Qt based applications.
* The front end GUI should make use of the model (and possibly some helper methods/signals/slots) t make use of the model using QML and/or sailfish GUI stuff.

It should be possible to reuse the client-qt code or write your own wrapper around the service API.

An example call for the command line demo could be:
```
Demos/LookupPOI ../maps/nordrhein-westfalen 51.2 6.5 51.7 8 amenity_hospital amenity_hospital_building
```
The main call is `POIService::GetPOIsInArea()`. You find the same call in the client-qt library in POILookupModule. Looking at the *,h file, is looks like you have to use the signal slot mechanism by triggering the lookup with a call to lookupPOIRequest() and listening to the resulting signals for retrieving the result. Positive result would be a list of `LocationEntry` which you can visualize using its exported properties.

I hope this helps. If not, you should now be hopefully able to respond with more detailed questions.

**Comment by jialinxie** [comment]
Thank you, i tested LookupPOI command line demo similar with your example call, the output is correct!
sorry I have misunderstood this LookupPOI module before. 
Thank you again! :-)

**Comment by Karry** [comment]
Hi. 

My idea was to provide basic building blocks in client-qt library (C++) and move application specific stuffs to QML. Downside is that UI code (QML/JavaScript) may be complicated...

Let me explain what is happening in (OSM Scout for Sailfish) [Search page](https://github.com/Karry/osmscout-sailfish/blob/master/qml/pages/Search.qml). The main page components are [searchField](https://github.com/Karry/osmscout-sailfish/blob/master/qml/pages/Search.qml#L129) (SearchField type) with binded string property `searchString` and [suggestionView](https://github.com/Karry/osmscout-sailfish/blob/master/qml/pages/Search.qml#L303) (SilicaListView type). Page can have [three states](https://github.com/Karry/osmscout-sailfish/blob/master/qml/pages/Search.qml#L43):

 - **empty** - `suggestionView` model is setup to [poiTypesModel](https://github.com/Karry/osmscout-sailfish/blob/master/qml/pages/Search.qml#L338); list of POI types is displayed.
 - **poi** - `suggestionView` model is setup to [poiModel](https://github.com/Karry/osmscout-sailfish/blob/master/qml/pages/Search.qml#L363); list of near POIs of specific types is displayed
 - **search** - `suggestionView` model is setup to [searchModel](https://github.com/Karry/osmscout-sailfish/blob/master/qml/pages/Search.qml#L369); list of search result is displayed (based on free text lookup and address lookup)

State is changed in [onSearchStringChanged](https://github.com/Karry/osmscout-sailfish/blob/master/qml/pages/Search.qml#L71) slot - when searchString is empty, *empty* state is used; when seach string starts with `poi:` prefix, given string is parsed and *poi* state is used. *Search* state is used otherwise. Poi string is using simple syntax: `poi:<distance in meters>:<spase separated POI types>`. Using this, you can search everything that exists in the database, you are not limited to predefined POI types in `poiTypesModel`. For example string `poi:1000:amenity_post_box amenity_post_office amenity_post_office_building` will show you post boxes and post offices up to distance 1km around you.

You can update OSMScout2 demo with exactly the same mechanism ;-)

**Comment by Karry** [comment]
I just add short NearPOIModel descriptin to QML documentation: https://github.com/Framstag/libosmscout/pull/619

**Comment by jialinxie** [comment]
@Karry 
Thank you very much for explaining this [Search page](https://github.com/Karry/osmscout-sailfish/blob/master/qml/pages/Search.qml), now i have much clearer logic about this qml code. I will try to update OSMScout2 demo with this mechanism.

**Comment by Framstag** [comment]
@jialinxie Any improvements to the OSMScout2 demo is welcome. I have done the initial implementation and as far as I remember @Karry did some additions, too. However nobody is currently actively driving the development of the demo to show new features.

So, if you want to add new feature or even want to change the UX mechanics, just make a pull request. You also can rely on newer Qt features. The QML part is old and AFAIK some things may be simpler now because of recent additions. 

If you do changes to the client-qt library, you have to coordinate them with @Karry. But for the actual OSMScout2 code and the QML code your are free to act. It would be nice though, if you do not drop features, especially the hidden key driven options for light/dark mode, debugging etc... since they are helpful for manual testing.

Have fun!
