### ISSUE TITLE
Wrong WaterIndex generated by BasemapImport

### ISSUE THREAD

**Issue by vyskocil** [Framstag/libosmscout#754]
When I render the water.idx computed by BasemapImport there are large holes and sometimes small rectangle missing and the patterns evolve when zooming.
It seems that large holes surround small islands.

Here are some sample screenshots : 

![IMG_0027](https://user-images.githubusercontent.com/452704/59969677-eba82400-9553-11e9-83d2-cd274c45b7a8.jpg)
![IMG_0028](https://user-images.githubusercontent.com/452704/59969678-f19e0500-9553-11e9-8b2b-550507548cf4.jpg)
![IMG_0029](https://user-images.githubusercontent.com/452704/59969680-fe225d80-9553-11e9-99df-391bf8827f34.jpg)
![IMG_0030](https://user-images.githubusercontent.com/452704/59969681-024e7b00-9554-11e9-92b3-7a0e671a070d.jpg)

**Comment by Karry** [comment]
Hi. 

The huge "unknown holes" in oceans and seas are created by algorithm naturaly and it should be possible to fill it just by tuning imporr settings. 

Small rectangles around some coastlines is bug. I saw it already, but dont had time (motivation) to investigate it yet. I will try to fix it...

**Comment by Karry** [comment]
I just found why the problem is not visible with standard stylesheet - unknown color is same as water... `COLOR unknownColor = @waterColor;`

**Comment by vyskocil** [comment]
I compiled a new water index with this code using the following command line :

`./BasemapImport --destinationDirectory world --coastlines coastlines-split-4326/lines.shp  --maxIndexLevel 12`

At lower zoom levels the basemap seems ok but when I zoom in I got the following map : 

![IMG_0031](https://user-images.githubusercontent.com/452704/60140216-3f637900-97b1-11e9-979b-20459168309a.PNG)

**Comment by Karry** [comment]
@vyskocil this issue is well known for me. problem is that coastlines sometimes intersect with each other after simplification and algorithm then badly evaluate water/land tiles, because it is expecting that coastlines don't intersects. This change with of parameter makes this problem "global". 

For that reason, I updated pre-processing method that is removing smaller objects when intersection is detected. https://github.com/Framstag/libosmscout/pull/758 In the past, these intersections was checked just for ways vs. areas, but in basemap, even continents are areas... So I sorted all objects by its size and then check first 100...

I made this change yesterday already, but was worry about performance. So during night I was running import of Canada. It tooks ~ 24 hours with master, but just 3 hours after that change - probably bounding box check improves it...

**Comment by Karry** [comment]
Hi. 

Most visible problems should be solved by: https://github.com/Framstag/libosmscout/pull/758 and https://github.com/Framstag/libosmscout/pull/762

@vyskocil can you please verify it?

**Comment by Framstag** [comment]
Everything by @Karry is now merged...

**Comment by vyskocil** [comment]
I just checked the latest code and build a new basemap like this :

$  ./BasemapImport --destinationDirectory world --coastlines coastlines-split-4326/lines.shp  --maxIndexLevel 12

The basemap seems perfect until a zoom level but after that some big part of the continents are outlined, this is strange that these error arise when zooming !

![IMG_0044](https://user-images.githubusercontent.com/452704/60808816-7b231900-a189-11e9-9711-b9ea024439d5.PNG)

![IMG_2D7F64F173DC-1](https://user-images.githubusercontent.com/452704/60808822-81b19080-a189-11e9-9fb9-8be962cfc02f.jpeg)

**Comment by Karry** [comment]
Interesting, I cannot reproduce it with the shapefile that I downloaded week ago. Can you try it please?
https://osmscout.karry.cz/tests/world/lines.shp

...and can you upload yours somewhere? 

Currently, processor is checking just 100 biggest objects for intersections (performance reason). Can you please try to increase that constant? https://github.com/Framstag/libosmscout/blob/master/libosmscout-import/src/osmscout/import/WaterIndexProcessor.cpp#L1263 Your flood is caused by some intersecting island probably :-/

**Comment by vyskocil** [comment]
I tried with https://osmscout.karry.cz/tests/world/lines.shp and the result was the same.
Then I changed the constant from 100 to 500 with the same result.
Then I tried to remove the --maxIndexLevel 12 in the command line and this time the issue vanished !

**Comment by vyskocil** [comment]
With --maxIndexLevel 11 it is still ok

**Comment by Framstag** [comment]
@vyskocil: Please check, if problems remain

**Comment by vyskocil** [comment]
It is ok now, thanks !
