### ISSUE TITLE
Libsmscout .dll System Error on Windows 10

### ISSUE THREAD

**Issue by bhomaidan1990** [Framstag/libosmscout#786]
When I start to debug any application of Libsmscout such as Comman Line Parsing.exe I get the following Error:
System Error
Error : The Code Excution cannot proceed because osmcout.dll was not found. Reinstalling the Program may fix this Problem.

I use VS2019 , Windows 10, also Tried Qt_5.13.1, but I have got many weird errors !
I even couldn't Build CMake with Qt, but I did with VS2019 !

**Comment by Framstag** [comment]
I check again using my Visual Studio 2017 build and cmake. You have to add the build libraries (or better: the directories containing the build DLLs) to the OS search path to get them found.

Depending on OS and build tool the *.exe is in fact a script that wraps the search path setting for you, but that is currently not the case for this combination.

Of course any improvement to the build script in this or other regards is helpful :-)

We have a number of Windows based builds here: https://ci.appveyor.com/project/Framstag/libosmscout

As you can see we currebtly have problems with the VisualStudio 2015/cmake combination that I cannot fix, since I cannot reproduce it under Visual Studio 2017 locally.

We also use vcpkg for supplying depependencies for cmake builds, which in principle proofs to be time consuming but assures that we have consistent builds. So I would recommend to use vcpkg if possible and acceptable.

The vcpkg stuff though is currently also broken in the central builds for unknown reasons (I assume integration by appveyor has some problem?).

**Comment by Framstag** [comment]
@bhomaidan1990 Does my answer help you? If not, please give more feedback? Can we close the issue?

**Comment by bhomaidan1990** [comment]
Yes thanks
