### ISSUE TITLE
Import problems

### ISSUE THREAD

**Issue by OgreTransporter** [Framstag/libosmscout#959]
I could not import some PBFs (Geofabrik e.g. spain-latest, us-midwest-latest, us-northeast-latest, us-south-latest, us-west-latest) - the import was aborted with error messages.

Import:
```
Import.exe --typefile D:\libosmscout\install\share\stylesheets\map.ost --destinationDirectory D:\Importtest\map --delete-temporary-files true spain-latest.osm.pbf
```

Log: https://pastebin.com/fAGU8PZy

Ressources: Max 10% cpu load on one of 4/8 cores and 1.7 GB RAM of 32 GB.

**Comment by Framstag** [comment]
I'm currently running a valgrind check for the importer for spain. I recently had strange effects around file access (tried to implement non-memory mapped version of ReadString against a static buffer to improve performance) so my intuition signals, that this may be wise to check (while being way from computer ;-)).

**Comment by Framstag** [comment]
The normal output would have been (with a huge gap of output skipped):

```
+ Step #6 - RelAreaDataGenerator...
   Module description: Resolves raw relations to areas
   Module requires file 'coord.dat'
   Module requires file 'rawways.dat'
   Module requires file 'rawrels.dat'
   Module requires file 'rawway.idx'
   Module requires file 'rawrel.idx'
   Module provides temporary file 'relarea.tmp'
   Module provides temporary file 'wayareablack.dat'
 - Generate relarea.tmp...
   !! Cannot resolve way member 96562964 for relation 7413 boundary_county 
   !! Cannot resolve way member 208557119 for relation 7439 boundary_county 
[...]
  lez_any: 0 0 0 0
   group_any: 0 0 0 0
   set_any: 0 0 0 0
   compound_any: 0 0 0 0
   => 369.019s, RSS 4,1 GiB, VM 4,4 GiB

```
but the log is:

```
+ Step #6 - RelAreaDataGenerator...
   Module description: Resolves raw relations to areas
   Module requires file 'coord.dat'
   Module requires file 'rawways.dat'
   Module requires file 'rawrels.dat'
   Module requires file 'rawway.idx'
   Module requires file 'rawrel.idx'
   Module provides temporary file 'relarea.tmp'
   Module provides temporary file 'wayareablack.dat'
   => 0.057s
   !! Import failed: File 'D:\Importtest\map\relarea.tmp' - Opening file: No such file or directory
 ```

That is the code that executes the module:

```
        ImportModuleDescription moduleDescription;
        bool                    success;

        module->GetDescription(parameter,
                               moduleDescription);

        progress.StartModule(currentStep, moduleDescription);

        success=module->Import(typeConfig,
                               parameter,
                               progress);

        progress.FinishedModule();

        if (!success) {
          progress.Error("Error while executing step '"+moduleDescription.GetName()+"'!");
          return false;
        }
```

The "=> XXX" output is generated by (StatImportProgress): progress.FinishedModule(). The "Import failed" seems to be generated by 

```
  catch (osmscout::IOException& e) {
    progress.Error("Import failed: "+e.GetDescription());
    exitCode=1;
  }
```

In the Import executable itself.

I assume that the error is generated by the following code, which is called after each module is execucted:

```
        if (parameter.IsEco()) {
          if (!CleanupTemporaries(currentStep,
                                  progress)) {
            return false;
          }
        }
```

@OgreTransporter: Do you possibly have eco modus activated? However, the eco modus handling code should not throw IO Exceptions... I'm not sure if the exception is generated form within the import module code or from around it.

The import module itself only calls:

```
      scanner.Open(AppendFileToDir(parameter.GetDestinationDirectory(),
                                   Preprocess::RAWRELS_DAT),
                   FileScanner::Sequential,
                   true);
```

Why should this fail? Also this code is wrapped in a try..catch.

**Comment by Framstag** [comment]
Btw., the Valgrind check is not finished, but importer is already at step 23, so even, if it still find an issue, it should not be relevant for above problem.

**Comment by OgreTransporter** [comment]
> @OgreTransporter: Do you possibly have eco modus activated? However, the eco modus handling code should not throw IO Exceptions... I'm not sure if the exception is generated form within the import module code or from around it.
> 
> The import module itself only calls:
> 
> ```
>       scanner.Open(AppendFileToDir(parameter.GetDestinationDirectory(),
>                                    Preprocess::RAWRELS_DAT),
>                    FileScanner::Sequential,
>                    true);
> ```
> 
> Why should this fail? Also this code is wrapped in a try..catch.

@Framstag No, I have not activated the eco-mode. The command line parameters can be seen at the top of the first post.
```
Import.exe --typefile D:\libosmscout\install\share\stylesheets\map.ost --destinationDirectory D:\Importtest\map --delete-temporary-files true spain-latest.osm.pbf
```

**Comment by Framstag** [comment]
I'M trying to reproduce the error, but already have problems reading *.osm.pbf files. The header type does not match "OSMHeader". It looks like this is a problem with protobuf itself. Did you use vcpkg (like I do) to build the Importer? Which Version of VisualStudio are you using?

**Comment by OgreTransporter** [comment]
No, I don't use vcpkg. I have a Jenkins server running that regularly builds new versions of now 130 libraries with Visual Studio 2017 and 2019. For the test I used 2017.

**Comment by Framstag** [comment]
Own Jenkins server, I'm impressed :-)

OK, my setup is vcpkg and VisualStudo 2019 (current version). In my case the PBF import already is not able to read the OSMHeader block type (See https://wiki.openstreetmap.org/wiki/DE:PBF_Format for a detailed description of the format, especially that OSMHeader is only a few bytes into the file). Since this is a problem that I do not have under Linux or Mac OS or MSYS, it looks like a specific problem with protobuf as build by vcpkg (and yes, all platform use x64). The *.xml import under Windows is a performance nightmare, even for small areas - and likely does not help to reproduce your specific problem...

I'm not sure how to proceed ob my side with reasonable effort. Any suggestions? Are able to debug the problem on your side?

**Comment by Framstag** [comment]
I tried to get a working Importer with PBF support also using meson wrap and conan (these are in principle alternative to vcpkg). In both cases I failed :-/

Next step would be to manually build protobuf. This is in principle not a sustainable approach for me, but I would like to have this bug fixed :-/ I'll see, when I'll have time for this.

Any effort on your side is still welcome :-)

**Comment by OgreTransporter** [comment]
I looked at the protobuf locations in osmscout/import/PreprocessPBF.cpp (128, 156, 205, 233 and 282), and it works fine for me.

An error in my case is in CoordDataFile.cpp (58):
```
FileOffset mapOffset=scanner.ReadFileOffset();
pageSize=scanner.ReadUInt32();

scanner.SetPos(mapOffset);
```
mapOffset=2450675712
pageSize=64

The function `SetPos` fails. I have found an error in https://github.com/Framstag/libosmscout/blob/f93cd01cd3683d3b4aef1807afca845d4bce0a00/libosmscout/src/osmscout/util/FileScanner.cpp#L377

In `HAVE__FSEEKI64` the **i** must be written in capital letters. `fseek` (https://docs.microsoft.com/de-de/cpp/c-runtime-library/reference/fseek-fseeki64) uses under Windows a 4 byte long for the position, whose maximum value is 2147483647 (https://docs.microsoft.com/en-us/cpp/cpp/data-type-ranges) - which is below the calculated offset of 2450675712. With _fseeki64 an 8 byte integer is used, which should be sufficient for all files.

I have completely imported Spain for testing - which works now. The files for the USA are also too big for 4 bytes, but with 8 it works.

**Comment by Framstag** [comment]
<Slap hand to head>. Thank you :-) Though the problem sounds simple this would have taken me a while. Many thanks for taking a look :-)

**Comment by OgreTransporter** [comment]
Careful, this only solves my problem! This does not solve the problem with Protobuf.

**Comment by OgreTransporter** [comment]
I am not a fan of vcpkg. The packages are not always up to date and there is no control over features/dependencies that can be enabled as CMake option. Some of them are also "patched" for vcpkg. The fact that I build the packages by Jenkins has also the advantage that I found a lot of bugs.

**Comment by Framstag** [comment]
I would not say, that I'm a fan of vcpkg either. There are through some positive aspects:
* Has all packages we need
* Easy integration in cmake

Negative points I see:
* Does not currently offer precompiled packages so our build take too long
* Obviously packages make problems and possibly have bugs.
* Qt5 builds are a nightmare, because of "only local builds".

Alternatives that help, too are:
* conan => Support binary packages, but possibly not all we need. Currently cmake only.
* wrapdb => Code only, not all packages we need, meson only. Packages seem to not build on all platforms (See https://github.com/mesonbuild/protobuf/issues/14)

I tried also the nuget way (a while ago), but this is even worse.

For both I have code and I can setup another build (since code is mostly there), but should I? For which platform?

The currently first goal of the builds is to make sure, that we continuously build on all supported platforms and do not leave a platform behind. So software must *build*. That the software actually *works*, is of course also important, but not as important. Also for this we would need a bigger test suite that we currently do not have. However you still benefit of a working vcpkg based build - even if it the resulting code does not work. So not everything is as bad as it sounds.

People at least have a rather simple recipy to get things to build.

Building all packages yourself is of course better, but how to integrate in to the CI systems we use?

In fact Linux and Mac OS (brew) are most of the time a problem. Window still is. And it looks like there is no perfect solution but only best effort.

**Comment by OgreTransporter** [comment]
With vcpkg we don't need our own builds. vcpkg packages are nothing more than special CMake scripts - that's why the integration is so easy. You simply specify a release status at GitHub and vcpkg will load the code and build it.

There is no need to rebuild packages after every PR. In fact, you only need to rebuild them for new releases.
