### ISSUE TITLE
Building iOS xcode project

### ISSUE THREAD

**Issue by ivanoikon** [Framstag/libosmscout#998]
I try to build and run iOS xcode project under Apple/OSMScoutOSX. I follow your documentation and the README.Apple.txt (seems outdated) but i get a lot of errors in Database.h.
Is there a way to have a working iOS example? Or to generate frameworks/library for iOS? I can't find it in the documentation and "cmake -G "Xcode" .." seems for OSX only.
Thanks in advance

**Comment by Framstag** [comment]
Hello :-)

We support meson and cmake as build tools for building libosmscout. Both also should work under OS X. 

I suggest to look at the actual CI build scripts to see, how to build libosmscout.

CMake:
https://github.com/Framstag/libosmscout/blob/master/.github/workflows/build_and%20test_on_osx_cmake.yml

Meson:
https://github.com/Framstag/libosmscout/blob/master/.github/workflows/build_and%20test_on_osx_meson.yml

CMake+iOS:
https://github.com/Framstag/libosmscout/blob/master/.github/workflows/build_and%20test_on_ios_cmake.yml

We do not have a tutorial to directly use libosmscout from within XCode. But above builds should help on this. If you can offer such tutorial, this would of course of great help :-)

If you have further questions, just ask.

For more complicated issue you can also use the mailing list.

Please close the issue, if your problem is solved.

**Comment by Framstag** [comment]
I'm no expert on XCode nor iOS development. I assume that it is wise to first develop under OS X and later on switch to IOS. This of course would require to have the necessary frameworks under iOS, too.

Libosmscout does require c++17 support. The iOS backend is a AFAIK mixure of object c and C++17 files. This might explain, why "just importing" is difficult. I assume that XCode cannot handle this automatically.

You can try to generate a XCode project using cmake XCode generator. See https://cmake.org/cmake/help/latest/generator/Xcode.html. We can assist you in this.

This in principle should assure that XCode has the correct language settings per file. This likely works for OS X, I'm not sure if this will work for iOS (due to the individual complexity of the participating tools).

I'm sure that @vyskocil has/had a working setup (he it the author of the iOSX backend). However he is not very fast in responding (IMHO due to work, travel,...). 

I have a Mac Book, however I'm no active OS X developer (especially not using XCode, though it is installed). I may help in libosmscout-specific details, if I'm able to follow your steps.

**Comment by Framstag** [comment]
See #999

**Comment by Framstag** [comment]
I was able to export a xcode project from cmake, import it into xcode and get a successfully build (see #999 for one workaround needed).

**Comment by Framstag** [comment]
@ivanoikon Can we close the issue? Do you still need help?
